// AUTO-GENERATED — do not edit by hand.

// Source: streams.d.ts

// Run: npx ts-node generate-model-details.ts --input ... --type StreamOptionsByProviderAndModel --type StreamFunctionByProviderAndModel --output ...

import { Type, type Static } from "@sinclair/typebox";

/** 83 duplicates: amazon.nova-2-lite-v1:0, amazon.nova-lite-v1:0, amazon.nova-micro-v1:0, amazon.nova-premier-v1:0, amazon.nova-pro-v1:0, anthropic.claude-3-5-haiku-20241022-v1:0, anthropic.claude-3-5-sonnet-20240620-v1:0, anthropic.claude-3-5-sonnet-20241022-v2:0, anthropic.claude-3-7-sonnet-20250219-v1:0, anthropic.claude-3-haiku-20240307-v1:0, anthropic.claude-haiku-4-5-20251001-v1:0, anthropic.claude-opus-4-1-20250805-v1:0, anthropic.claude-opus-4-20250514-v1:0, anthropic.claude-opus-4-5-20251101-v1:0, anthropic.claude-opus-4-6-v1, anthropic.claude-sonnet-4-20250514-v1:0, anthropic.claude-sonnet-4-5-20250929-v1:0, anthropic.claude-sonnet-4-6, deepseek.r1-v1:0, deepseek.v3-v1:0, deepseek.v3.2, eu.anthropic.claude-haiku-4-5-20251001-v1:0, eu.anthropic.claude-opus-4-5-20251101-v1:0, eu.anthropic.claude-opus-4-6-v1, eu.anthropic.claude-sonnet-4-20250514-v1:0, eu.anthropic.claude-sonnet-4-5-20250929-v1:0, eu.anthropic.claude-sonnet-4-6, global.anthropic.claude-haiku-4-5-20251001-v1:0, global.anthropic.claude-opus-4-5-20251101-v1:0, global.anthropic.claude-opus-4-6-v1, global.anthropic.claude-sonnet-4-20250514-v1:0, global.anthropic.claude-sonnet-4-5-20250929-v1:0, global.anthropic.claude-sonnet-4-6, google.gemma-3-27b-it, google.gemma-3-4b-it, meta.llama3-1-405b-instruct-v1:0, meta.llama3-1-70b-instruct-v1:0, meta.llama3-1-8b-instruct-v1:0, meta.llama3-2-11b-instruct-v1:0, meta.llama3-2-1b-instruct-v1:0, meta.llama3-2-3b-instruct-v1:0, meta.llama3-2-90b-instruct-v1:0, meta.llama3-3-70b-instruct-v1:0, meta.llama4-maverick-17b-instruct-v1:0, meta.llama4-scout-17b-instruct-v1:0, minimax.minimax-m2, minimax.minimax-m2.1, mistral.devstral-2-123b, mistral.magistral-small-2509, mistral.ministral-3-14b-instruct, mistral.ministral-3-3b-instruct, mistral.ministral-3-8b-instruct, mistral.mistral-large-3-675b-instruct, mistral.pixtral-large-2502-v1:0, mistral.voxtral-mini-3b-2507, mistral.voxtral-small-24b-2507, moonshot.kimi-k2-thinking, moonshotai.kimi-k2.5, nvidia.nemotron-nano-12b-v2, nvidia.nemotron-nano-3-30b, nvidia.nemotron-nano-9b-v2, openai.gpt-oss-120b-1:0, openai.gpt-oss-20b-1:0, openai.gpt-oss-safeguard-120b, openai.gpt-oss-safeguard-20b, qwen.qwen3-235b-a22b-2507-v1:0, qwen.qwen3-32b-v1:0, qwen.qwen3-coder-30b-a3b-v1:0, qwen.qwen3-coder-480b-a35b-v1:0, qwen.qwen3-next-80b-a3b, qwen.qwen3-vl-235b-a22b, us.anthropic.claude-haiku-4-5-20251001-v1:0, us.anthropic.claude-opus-4-1-20250805-v1:0, us.anthropic.claude-opus-4-20250514-v1:0, us.anthropic.claude-opus-4-5-20251101-v1:0, us.anthropic.claude-opus-4-6-v1, us.anthropic.claude-sonnet-4-20250514-v1:0, us.anthropic.claude-sonnet-4-5-20250929-v1:0, us.anthropic.claude-sonnet-4-6, writer.palmyra-x4-v1:0, writer.palmyra-x5-v1:0, zai.glm-4.7, zai.glm-4.7-flash */
const _obj0 = Type.Object({
maxTokens: Type.Optional(Type.Number()),
headers: Type.Optional(Type.Object({},
{
additionalProperties: Type.String()
 })),
temperature: Type.Optional(Type.Number()),
apiKey: Type.Optional(Type.String()),
transport: Type.Optional(Type.Union([
Type.Literal("sse"),
Type.Literal("websocket"),
Type.Literal("auto")
])),
cacheRetention: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("short"),
Type.Literal("long")
])),
sessionId: Type.Optional(Type.String()),
maxRetryDelayMs: Type.Optional(Type.Number()),
metadata: Type.Optional(Type.Object({},
{
additionalProperties: Type.Unknown()
 }))
});
/** 182 duplicates: claude-3-5-haiku-20241022, claude-3-5-haiku-latest, claude-3-5-sonnet-20240620, claude-3-5-sonnet-20241022, claude-3-7-sonnet-20250219, claude-3-7-sonnet-latest, claude-3-haiku-20240307, claude-3-opus-20240229, claude-3-sonnet-20240229, claude-haiku-4-5, claude-haiku-4-5-20251001, claude-opus-4-0, claude-opus-4-1, claude-opus-4-1-20250805, claude-opus-4-20250514, claude-opus-4-5, claude-opus-4-5-20251101, claude-opus-4-6, claude-sonnet-4-0, claude-sonnet-4-20250514, claude-sonnet-4-5, claude-sonnet-4-5-20250929, claude-sonnet-4-6, claude-haiku-4.5, claude-opus-4.5, claude-opus-4.6, claude-sonnet-4, claude-sonnet-4.5, claude-sonnet-4.6, openai/gpt-oss-20b, anthropic/claude-3-haiku, anthropic/claude-3.5-haiku, anthropic/claude-3.5-sonnet, anthropic/claude-3.7-sonnet, anthropic/claude-haiku-4.5, anthropic/claude-opus-4, anthropic/claude-opus-4.1, anthropic/claude-opus-4.5, anthropic/claude-opus-4.6, anthropic/claude-sonnet-4, anthropic/claude-sonnet-4.5, anthropic/claude-sonnet-4.6, deepseek/deepseek-r1, deepseek/deepseek-v3.1-terminus, deepseek/deepseek-v3.2, google/gemini-2.5-flash, google/gemini-2.5-flash-lite, google/gemini-2.5-pro, google/gemini-3-pro-preview, google/gemini-3.1-flash-lite-preview, google/gemini-3.1-pro-preview, inception/mercury-2, meituan/longcat-flash-chat, minimax/minimax-m2, minimax/minimax-m2.1, minimax/minimax-m2.5, moonshotai/kimi-k2, moonshotai/kimi-k2-0905, moonshotai/kimi-k2-thinking, moonshotai/kimi-k2.5, nvidia/nemotron-nano-9b-v2, openai/gpt-4-turbo, openai/gpt-4.1, openai/gpt-4.1-mini, openai/gpt-4.1-nano, openai/gpt-4o, openai/gpt-4o-mini, openai/gpt-5, openai/gpt-5-codex, openai/gpt-5-mini, openai/gpt-5-nano, openai/gpt-5-pro, openai/gpt-5.1-codex, openai/gpt-5.1-codex-max, openai/gpt-5.1-codex-mini, openai/gpt-5.2, openai/gpt-5.2-chat, openai/gpt-5.2-codex, openai/gpt-5.2-pro, openai/gpt-5.3-chat, openai/gpt-5.3-codex, openai/gpt-5.4, openai/gpt-5.4-mini, openai/gpt-5.4-nano, openai/gpt-5.4-pro, openai/gpt-oss-safeguard-20b, openai/o1, openai/o3, openai/o3-deep-research, openai/o3-mini, openai/o3-pro, openai/o4-mini, prime-intellect/intellect-3, xiaomi/mimo-v2-flash, alibaba/qwen-3-14b, alibaba/qwen-3-235b, alibaba/qwen-3-30b, alibaba/qwen-3-32b, alibaba/qwen3-235b-a22b-thinking, alibaba/qwen3-coder, alibaba/qwen3-coder-30b-a3b, alibaba/qwen3-coder-next, alibaba/qwen3-coder-plus, alibaba/qwen3-max, alibaba/qwen3-max-preview, alibaba/qwen3-max-thinking, alibaba/qwen3-vl-thinking, alibaba/qwen3.5-flash, alibaba/qwen3.5-plus, anthropic/claude-3.5-sonnet-20240620, arcee-ai/trinity-large-preview, bytedance/seed-1.6, cohere/command-a, deepseek/deepseek-v3, deepseek/deepseek-v3.1, deepseek/deepseek-v3.2-thinking, google/gemini-2.0-flash, google/gemini-2.0-flash-lite, google/gemini-3-flash, inception/mercury-coder-small, meituan/longcat-flash-thinking, meta/llama-3.1-70b, meta/llama-3.1-8b, meta/llama-3.2-11b, meta/llama-3.2-90b, meta/llama-3.3-70b, meta/llama-4-maverick, meta/llama-4-scout, minimax/minimax-m2.1-lightning, minimax/minimax-m2.5-highspeed, mistral/codestral, mistral/devstral-2, mistral/devstral-small, mistral/devstral-small-2, mistral/ministral-3b, mistral/ministral-8b, mistral/mistral-medium, mistral/mistral-small, mistral/pixtral-12b, mistral/pixtral-large, moonshotai/kimi-k2-thinking-turbo, moonshotai/kimi-k2-turbo, nvidia/nemotron-nano-12b-v2-vl, openai/gpt-5-chat, openai/gpt-5.1-instant, openai/gpt-5.1-thinking, perplexity/sonar, perplexity/sonar-pro, xai/grok-2-vision, xai/grok-3, xai/grok-3-fast, xai/grok-3-mini, xai/grok-3-mini-fast, xai/grok-4, xai/grok-4-fast-non-reasoning, xai/grok-4-fast-reasoning, xai/grok-4.1-fast-non-reasoning, xai/grok-4.1-fast-reasoning, xai/grok-4.20-multi-agent-beta, xai/grok-4.20-non-reasoning-beta, xai/grok-4.20-reasoning-beta, xai/grok-code-fast-1, zai/glm-4.5, zai/glm-4.5-air, zai/glm-4.5v, zai/glm-4.6, zai/glm-4.6v, zai/glm-4.6v-flash, zai/glm-4.7, zai/glm-4.7-flash, zai/glm-4.7-flashx, zai/glm-5, zai/glm-5-turbo, MiniMax-M2, MiniMax-M2.1, MiniMax-M2.5, MiniMax-M2.5-highspeed, big-pickle, claude-3-5-haiku, minimax-m2.5-free, minimax-m2.5, kimi-k2-thinking */
const _obj1 = Type.Object({
effort: Type.Optional(Type.Union([
Type.Literal("low"),
Type.Literal("medium"),
Type.Literal("high"),
Type.Literal("max")
])),
maxTokens: Type.Optional(Type.Number()),
headers: Type.Optional(Type.Object({},
{
additionalProperties: Type.String()
 })),
temperature: Type.Optional(Type.Number()),
apiKey: Type.Optional(Type.String()),
transport: Type.Optional(Type.Union([
Type.Literal("sse"),
Type.Literal("websocket"),
Type.Literal("auto")
])),
cacheRetention: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("short"),
Type.Literal("long")
])),
sessionId: Type.Optional(Type.String()),
maxRetryDelayMs: Type.Optional(Type.Number()),
metadata: Type.Optional(Type.Object({},
{
additionalProperties: Type.Unknown()
 })),
thinkingEnabled: Type.Optional(Type.Boolean()),
thinkingBudgetTokens: Type.Optional(Type.Number()),
interleavedThinking: Type.Optional(Type.Boolean()),
toolChoice: Type.Optional(Type.Union([
Type.Literal("auto"),
Type.Literal("none"),
Type.Literal("any"),
Type.Object({
type: Type.Literal("tool"),
name: Type.String()
})
]))
});
/** 26 duplicates: gemini-1.5-flash, gemini-1.5-flash-8b, gemini-1.5-pro, gemini-2.0-flash, gemini-2.0-flash-lite, gemini-2.5-flash, gemini-2.5-flash-lite, gemini-2.5-flash-lite-preview-06-17, gemini-2.5-flash-lite-preview-09-2025, gemini-2.5-flash-preview-04-17, gemini-2.5-flash-preview-05-20, gemini-2.5-flash-preview-09-2025, gemini-2.5-pro, gemini-2.5-pro-preview-05-06, gemini-2.5-pro-preview-06-05, gemini-3-flash-preview, gemini-3-pro-preview, gemini-3.1-flash-lite-preview, gemini-3.1-pro-preview, gemini-3.1-pro-preview-customtools, gemini-flash-latest, gemini-flash-lite-latest, gemini-live-2.5-flash, gemini-live-2.5-flash-preview-native-audio, gemini-3-flash, gemini-3.1-pro */
const _obj2 = Type.Object({
maxTokens: Type.Optional(Type.Number()),
headers: Type.Optional(Type.Object({},
{
additionalProperties: Type.String()
 })),
temperature: Type.Optional(Type.Number()),
apiKey: Type.Optional(Type.String()),
transport: Type.Optional(Type.Union([
Type.Literal("sse"),
Type.Literal("websocket"),
Type.Literal("auto")
])),
cacheRetention: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("short"),
Type.Literal("long")
])),
sessionId: Type.Optional(Type.String()),
maxRetryDelayMs: Type.Optional(Type.Number()),
metadata: Type.Optional(Type.Object({},
{
additionalProperties: Type.Unknown()
 })),
toolChoice: Type.Optional(Type.Union([
Type.Literal("auto"),
Type.Literal("none"),
Type.Literal("any")
])),
thinking: Type.Optional(Type.Object({
enabled: Type.Boolean(),
budgetTokens: Type.Optional(Type.Number()),
level: Type.Optional(Type.Union([
Type.Literal("THINKING_LEVEL_UNSPECIFIED"),
Type.Literal("MINIMAL"),
Type.Literal("LOW"),
Type.Literal("MEDIUM"),
Type.Literal("HIGH")
]))
}))
});
/** 15 duplicates: gemini-2.0-flash, gemini-2.5-flash, gemini-2.5-pro, gemini-3-flash-preview, gemini-3-pro-preview, gemini-3.1-pro-preview, claude-sonnet-4-5, claude-sonnet-4-6, claude-opus-4-5-thinking, claude-opus-4-6-thinking, claude-sonnet-4-5-thinking, gemini-3-flash, gemini-3.1-pro-high, gemini-3.1-pro-low, gpt-oss-120b-medium */
const _obj3 = Type.Object({
maxTokens: Type.Optional(Type.Number()),
headers: Type.Optional(Type.Object({},
{
additionalProperties: Type.String()
 })),
temperature: Type.Optional(Type.Number()),
apiKey: Type.Optional(Type.String()),
transport: Type.Optional(Type.Union([
Type.Literal("sse"),
Type.Literal("websocket"),
Type.Literal("auto")
])),
cacheRetention: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("short"),
Type.Literal("long")
])),
sessionId: Type.Optional(Type.String()),
maxRetryDelayMs: Type.Optional(Type.Number()),
metadata: Type.Optional(Type.Object({},
{
additionalProperties: Type.Unknown()
 })),
toolChoice: Type.Optional(Type.Union([
Type.Literal("auto"),
Type.Literal("none"),
Type.Literal("any")
])),
thinking: Type.Optional(Type.Object({
enabled: Type.Boolean(),
budgetTokens: Type.Optional(Type.Number()),
level: Type.Optional(Type.Union([
Type.Literal("THINKING_LEVEL_UNSPECIFIED"),
Type.Literal("MINIMAL"),
Type.Literal("LOW"),
Type.Literal("MEDIUM"),
Type.Literal("HIGH")
]))
})),
projectId: Type.Optional(Type.String())
});
/** 12 duplicates: gemini-1.5-flash, gemini-1.5-flash-8b, gemini-1.5-pro, gemini-2.0-flash, gemini-2.0-flash-lite, gemini-2.5-flash, gemini-2.5-flash-lite, gemini-2.5-flash-lite-preview-09-2025, gemini-2.5-pro, gemini-3-flash-preview, gemini-3-pro-preview, gemini-3.1-pro-preview */
const _obj4 = Type.Object({
maxTokens: Type.Optional(Type.Number()),
headers: Type.Optional(Type.Object({},
{
additionalProperties: Type.String()
 })),
temperature: Type.Optional(Type.Number()),
apiKey: Type.Optional(Type.String()),
transport: Type.Optional(Type.Union([
Type.Literal("sse"),
Type.Literal("websocket"),
Type.Literal("auto")
])),
cacheRetention: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("short"),
Type.Literal("long")
])),
sessionId: Type.Optional(Type.String()),
maxRetryDelayMs: Type.Optional(Type.Number()),
metadata: Type.Optional(Type.Object({},
{
additionalProperties: Type.Unknown()
 })),
toolChoice: Type.Optional(Type.Union([
Type.Literal("auto"),
Type.Literal("none"),
Type.Literal("any")
])),
thinking: Type.Optional(Type.Object({
enabled: Type.Boolean(),
budgetTokens: Type.Optional(Type.Number()),
level: Type.Optional(Type.Union([
Type.Literal("THINKING_LEVEL_UNSPECIFIED"),
Type.Literal("MINIMAL"),
Type.Literal("LOW"),
Type.Literal("MEDIUM"),
Type.Literal("HIGH")
]))
})),
project: Type.Optional(Type.String()),
location: Type.Optional(Type.String())
});
/** 38 duplicates: codex-mini-latest, gpt-4, gpt-4-turbo, gpt-4.1, gpt-4.1-mini, gpt-4.1-nano, gpt-4o, gpt-4o-2024-05-13, gpt-4o-2024-08-06, gpt-4o-2024-11-20, gpt-4o-mini, gpt-5, gpt-5-chat-latest, gpt-5-codex, gpt-5-mini, gpt-5-nano, gpt-5-pro, gpt-5.1, gpt-5.1-chat-latest, gpt-5.1-codex, gpt-5.1-codex-max, gpt-5.1-codex-mini, gpt-5.2, gpt-5.2-chat-latest, gpt-5.2-codex, gpt-5.2-pro, gpt-5.3-codex, gpt-5.3-codex-spark, gpt-5.4, gpt-5.4-mini, gpt-5.4-nano, gpt-5.4-pro, o1-pro, o3-deep-research, o3-mini, o3-pro, o4-mini, o4-mini-deep-research */
const _obj5 = Type.Object({
serviceTier: Type.Optional(Type.Union([
Type.Literal("auto"),
Type.Literal("default"),
Type.Literal("flex"),
Type.Literal("scale"),
Type.Literal("priority")
])),
maxTokens: Type.Optional(Type.Number()),
headers: Type.Optional(Type.Object({},
{
additionalProperties: Type.String()
 })),
temperature: Type.Optional(Type.Number()),
apiKey: Type.Optional(Type.String()),
transport: Type.Optional(Type.Union([
Type.Literal("sse"),
Type.Literal("websocket"),
Type.Literal("auto")
])),
cacheRetention: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("short"),
Type.Literal("long")
])),
sessionId: Type.Optional(Type.String()),
maxRetryDelayMs: Type.Optional(Type.Number()),
metadata: Type.Optional(Type.Object({},
{
additionalProperties: Type.Unknown()
 })),
reasoningEffort: Type.Optional(Type.Union([
Type.Literal("minimal"),
Type.Literal("low"),
Type.Literal("medium"),
Type.Literal("high"),
Type.Literal("xhigh")
])),
reasoningSummary: Type.Optional(Type.Union([
Type.Literal("auto"),
Type.Literal("detailed"),
Type.Literal("concise"),
Type.Null()
]))
});
/** 38 duplicates: codex-mini-latest, gpt-4, gpt-4-turbo, gpt-4.1, gpt-4.1-mini, gpt-4.1-nano, gpt-4o, gpt-4o-2024-05-13, gpt-4o-2024-08-06, gpt-4o-2024-11-20, gpt-4o-mini, gpt-5, gpt-5-chat-latest, gpt-5-codex, gpt-5-mini, gpt-5-nano, gpt-5-pro, gpt-5.1, gpt-5.1-chat-latest, gpt-5.1-codex, gpt-5.1-codex-max, gpt-5.1-codex-mini, gpt-5.2, gpt-5.2-chat-latest, gpt-5.2-codex, gpt-5.2-pro, gpt-5.3-codex, gpt-5.3-codex-spark, gpt-5.4, gpt-5.4-mini, gpt-5.4-nano, gpt-5.4-pro, o1-pro, o3-deep-research, o3-mini, o3-pro, o4-mini, o4-mini-deep-research */
const _obj6 = Type.Object({
maxTokens: Type.Optional(Type.Number()),
headers: Type.Optional(Type.Object({},
{
additionalProperties: Type.String()
 })),
temperature: Type.Optional(Type.Number()),
apiKey: Type.Optional(Type.String()),
transport: Type.Optional(Type.Union([
Type.Literal("sse"),
Type.Literal("websocket"),
Type.Literal("auto")
])),
cacheRetention: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("short"),
Type.Literal("long")
])),
sessionId: Type.Optional(Type.String()),
maxRetryDelayMs: Type.Optional(Type.Number()),
metadata: Type.Optional(Type.Object({},
{
additionalProperties: Type.Unknown()
 })),
reasoningEffort: Type.Optional(Type.Union([
Type.Literal("minimal"),
Type.Literal("low"),
Type.Literal("medium"),
Type.Literal("high"),
Type.Literal("xhigh")
])),
reasoningSummary: Type.Optional(Type.Union([
Type.Literal("auto"),
Type.Literal("detailed"),
Type.Literal("concise"),
Type.Null()
])),
azureApiVersion: Type.Optional(Type.String()),
azureResourceName: Type.Optional(Type.String()),
azureBaseUrl: Type.Optional(Type.String()),
azureDeploymentName: Type.Optional(Type.String())
});
/** 8 duplicates: gpt-5.1, gpt-5.1-codex-max, gpt-5.1-codex-mini, gpt-5.2, gpt-5.2-codex, gpt-5.3-codex, gpt-5.3-codex-spark, gpt-5.4 */
const _obj7 = Type.Object({
maxTokens: Type.Optional(Type.Number()),
headers: Type.Optional(Type.Object({},
{
additionalProperties: Type.String()
 })),
temperature: Type.Optional(Type.Number()),
apiKey: Type.Optional(Type.String()),
transport: Type.Optional(Type.Union([
Type.Literal("sse"),
Type.Literal("websocket"),
Type.Literal("auto")
])),
cacheRetention: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("short"),
Type.Literal("long")
])),
sessionId: Type.Optional(Type.String()),
maxRetryDelayMs: Type.Optional(Type.Number()),
metadata: Type.Optional(Type.Object({},
{
additionalProperties: Type.Unknown()
 })),
reasoningEffort: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("minimal"),
Type.Literal("low"),
Type.Literal("medium"),
Type.Literal("high"),
Type.Literal("xhigh")
])),
reasoningSummary: Type.Optional(Type.Union([
Type.Literal("auto"),
Type.Literal("concise"),
Type.Literal("detailed"),
Type.Literal("off"),
Type.Literal("on"),
Type.Null()
])),
textVerbosity: Type.Optional(Type.Union([
Type.Literal("low"),
Type.Literal("medium"),
Type.Literal("high")
]))
});
/** 324 duplicates: gemini-2.5-pro, gemini-3-flash-preview, gemini-3-pro-preview, gemini-3.1-pro-preview, gpt-4.1, gpt-4o, grok-code-fast-1, grok-2, grok-2-1212, grok-2-latest, grok-2-vision, grok-2-vision-1212, grok-2-vision-latest, grok-3, grok-3-fast, grok-3-fast-latest, grok-3-latest, grok-3-mini, grok-3-mini-fast, grok-3-mini-fast-latest, grok-3-mini-latest, grok-4, grok-4-1-fast, grok-4-1-fast-non-reasoning, grok-4-fast, grok-4-fast-non-reasoning, grok-4.20-beta-latest-non-reasoning, grok-4.20-beta-latest-reasoning, grok-4.20-multi-agent-beta-latest, grok-beta, grok-vision-beta, deepseek-r1-distill-llama-70b, gemma2-9b-it, llama-3.1-8b-instant, llama-3.3-70b-versatile, llama3-70b-8192, llama3-8b-8192, meta-llama/llama-4-maverick-17b-128e-instruct, meta-llama/llama-4-scout-17b-16e-instruct, mistral-saba-24b, moonshotai/kimi-k2-instruct, moonshotai/kimi-k2-instruct-0905, openai/gpt-oss-120b, openai/gpt-oss-20b, qwen-qwq-32b, qwen/qwen3-32b, gpt-oss-120b, llama3.1-8b, qwen-3-235b-a22b-instruct-2507, zai-glm-4.7, ai21/jamba-large-1.7, alibaba/tongyi-deepresearch-30b-a3b, allenai/olmo-3.1-32b-instruct, amazon/nova-2-lite-v1, amazon/nova-lite-v1, amazon/nova-micro-v1, amazon/nova-premier-v1, amazon/nova-pro-v1, anthropic/claude-3-haiku, anthropic/claude-3.5-haiku, anthropic/claude-3.5-sonnet, anthropic/claude-3.7-sonnet, anthropic/claude-3.7-sonnet:thinking, anthropic/claude-haiku-4.5, anthropic/claude-opus-4, anthropic/claude-opus-4.1, anthropic/claude-opus-4.5, anthropic/claude-opus-4.6, anthropic/claude-sonnet-4, anthropic/claude-sonnet-4.5, anthropic/claude-sonnet-4.6, arcee-ai/trinity-large-preview:free, arcee-ai/trinity-mini, arcee-ai/trinity-mini:free, arcee-ai/virtuoso-large, baidu/ernie-4.5-21b-a3b, baidu/ernie-4.5-vl-28b-a3b, bytedance-seed/seed-1.6, bytedance-seed/seed-1.6-flash, bytedance-seed/seed-2.0-lite, bytedance-seed/seed-2.0-mini, cohere/command-r-08-2024, cohere/command-r-plus-08-2024, deepseek/deepseek-chat, deepseek/deepseek-chat-v3-0324, deepseek/deepseek-chat-v3.1, deepseek/deepseek-r1, deepseek/deepseek-r1-0528, deepseek/deepseek-v3.1-terminus, deepseek/deepseek-v3.2, deepseek/deepseek-v3.2-exp, essentialai/rnj-1-instruct, google/gemini-2.0-flash-001, google/gemini-2.0-flash-lite-001, google/gemini-2.5-flash, google/gemini-2.5-flash-lite, google/gemini-2.5-flash-lite-preview-09-2025, google/gemini-2.5-pro, google/gemini-2.5-pro-preview, google/gemini-2.5-pro-preview-05-06, google/gemini-3-flash-preview, google/gemini-3-pro-preview, google/gemini-3.1-flash-lite-preview, google/gemini-3.1-pro-preview, google/gemini-3.1-pro-preview-customtools, google/gemma-3-27b-it, google/gemma-3-27b-it:free, inception/mercury, inception/mercury-2, inception/mercury-coder, kwaipilot/kat-coder-pro, meituan/longcat-flash-chat, meta-llama/llama-3-8b-instruct, meta-llama/llama-3.1-70b-instruct, meta-llama/llama-3.1-8b-instruct, meta-llama/llama-3.3-70b-instruct, meta-llama/llama-3.3-70b-instruct:free, meta-llama/llama-4-maverick, meta-llama/llama-4-scout, minimax/minimax-m1, minimax/minimax-m2, minimax/minimax-m2.1, minimax/minimax-m2.5, minimax/minimax-m2.5:free, mistralai/codestral-2508, mistralai/devstral-2512, mistralai/devstral-medium, mistralai/devstral-small, mistralai/ministral-14b-2512, mistralai/ministral-3b-2512, mistralai/ministral-8b-2512, mistralai/mistral-large, mistralai/mistral-large-2407, mistralai/mistral-large-2411, mistralai/mistral-large-2512, mistralai/mistral-medium-3, mistralai/mistral-medium-3.1, mistralai/mistral-nemo, mistralai/mistral-saba, mistralai/mistral-small-24b-instruct-2501, mistralai/mistral-small-2603, mistralai/mistral-small-3.1-24b-instruct:free, mistralai/mistral-small-3.2-24b-instruct, mistralai/mistral-small-creative, mistralai/mixtral-8x22b-instruct, mistralai/mixtral-8x7b-instruct, mistralai/pixtral-large-2411, mistralai/voxtral-small-24b-2507, moonshotai/kimi-k2, moonshotai/kimi-k2-0905, moonshotai/kimi-k2-thinking, moonshotai/kimi-k2.5, nex-agi/deepseek-v3.1-nex-n1, nvidia/llama-3.1-nemotron-70b-instruct, nvidia/llama-3.3-nemotron-super-49b-v1.5, nvidia/nemotron-3-nano-30b-a3b, nvidia/nemotron-3-nano-30b-a3b:free, nvidia/nemotron-3-super-120b-a12b:free, nvidia/nemotron-nano-12b-v2-vl:free, nvidia/nemotron-nano-9b-v2, nvidia/nemotron-nano-9b-v2:free, openai/gpt-3.5-turbo, openai/gpt-3.5-turbo-0613, openai/gpt-3.5-turbo-16k, openai/gpt-4, openai/gpt-4-0314, openai/gpt-4-1106-preview, openai/gpt-4-turbo, openai/gpt-4-turbo-preview, openai/gpt-4.1, openai/gpt-4.1-mini, openai/gpt-4.1-nano, openai/gpt-4o, openai/gpt-4o-2024-05-13, openai/gpt-4o-2024-08-06, openai/gpt-4o-2024-11-20, openai/gpt-4o-audio-preview, openai/gpt-4o-mini, openai/gpt-4o-mini-2024-07-18, openai/gpt-4o:extended, openai/gpt-5, openai/gpt-5-codex, openai/gpt-5-image, openai/gpt-5-image-mini, openai/gpt-5-mini, openai/gpt-5-nano, openai/gpt-5-pro, openai/gpt-5.1, openai/gpt-5.1-chat, openai/gpt-5.1-codex, openai/gpt-5.1-codex-max, openai/gpt-5.1-codex-mini, openai/gpt-5.2, openai/gpt-5.2-chat, openai/gpt-5.2-codex, openai/gpt-5.2-pro, openai/gpt-5.3-chat, openai/gpt-5.3-codex, openai/gpt-5.4, openai/gpt-5.4-mini, openai/gpt-5.4-nano, openai/gpt-5.4-pro, openai/gpt-oss-120b:free, openai/gpt-oss-20b:free, openai/gpt-oss-safeguard-20b, openai/o1, openai/o3, openai/o3-deep-research, openai/o3-mini, openai/o3-mini-high, openai/o3-pro, openai/o4-mini, openai/o4-mini-deep-research, openai/o4-mini-high, openrouter/auto, openrouter/free, openrouter/healer-alpha, openrouter/hunter-alpha, prime-intellect/intellect-3, qwen/qwen-2.5-72b-instruct, qwen/qwen-2.5-7b-instruct, qwen/qwen-max, qwen/qwen-plus, qwen/qwen-plus-2025-07-28, qwen/qwen-plus-2025-07-28:thinking, qwen/qwen-turbo, qwen/qwen-vl-max, qwen/qwen3-14b, qwen/qwen3-235b-a22b, qwen/qwen3-235b-a22b-2507, qwen/qwen3-235b-a22b-thinking-2507, qwen/qwen3-30b-a3b, qwen/qwen3-30b-a3b-instruct-2507, qwen/qwen3-30b-a3b-thinking-2507, qwen/qwen3-4b:free, qwen/qwen3-8b, qwen/qwen3-coder, qwen/qwen3-coder-30b-a3b-instruct, qwen/qwen3-coder-flash, qwen/qwen3-coder-next, qwen/qwen3-coder-plus, qwen/qwen3-coder:free, qwen/qwen3-max, qwen/qwen3-max-thinking, qwen/qwen3-next-80b-a3b-instruct, qwen/qwen3-next-80b-a3b-instruct:free, qwen/qwen3-next-80b-a3b-thinking, qwen/qwen3-vl-235b-a22b-instruct, qwen/qwen3-vl-235b-a22b-thinking, qwen/qwen3-vl-30b-a3b-instruct, qwen/qwen3-vl-30b-a3b-thinking, qwen/qwen3-vl-32b-instruct, qwen/qwen3-vl-8b-instruct, qwen/qwen3-vl-8b-thinking, qwen/qwen3.5-122b-a10b, qwen/qwen3.5-27b, qwen/qwen3.5-35b-a3b, qwen/qwen3.5-397b-a17b, qwen/qwen3.5-9b, qwen/qwen3.5-flash-02-23, qwen/qwen3.5-plus-02-15, qwen/qwq-32b, relace/relace-search, sao10k/l3-euryale-70b, sao10k/l3.1-euryale-70b, stepfun/step-3.5-flash, stepfun/step-3.5-flash:free, thedrummer/rocinante-12b, thedrummer/unslopnemo-12b, tngtech/deepseek-r1t2-chimera, upstage/solar-pro-3, x-ai/grok-3, x-ai/grok-3-beta, x-ai/grok-3-mini, x-ai/grok-3-mini-beta, x-ai/grok-4, x-ai/grok-4-fast, x-ai/grok-4.1-fast, x-ai/grok-4.20-beta, x-ai/grok-code-fast-1, xiaomi/mimo-v2-flash, z-ai/glm-4-32b, z-ai/glm-4.5, z-ai/glm-4.5-air, z-ai/glm-4.5-air:free, z-ai/glm-4.5v, z-ai/glm-4.6, z-ai/glm-4.6v, z-ai/glm-4.7, z-ai/glm-4.7-flash, z-ai/glm-5, z-ai/glm-5-turbo, glm-4.5, glm-4.5-air, glm-4.5-flash, glm-4.5v, glm-4.6, glm-4.6v, glm-4.7, glm-4.7-flash, glm-5, glm-5-turbo, MiniMaxAI/MiniMax-M2.1, MiniMaxAI/MiniMax-M2.5, Qwen/Qwen3-235B-A22B-Thinking-2507, Qwen/Qwen3-Coder-480B-A35B-Instruct, Qwen/Qwen3-Coder-Next, Qwen/Qwen3-Next-80B-A3B-Instruct, Qwen/Qwen3-Next-80B-A3B-Thinking, Qwen/Qwen3.5-397B-A17B, XiaomiMiMo/MiMo-V2-Flash, deepseek-ai/DeepSeek-R1-0528, deepseek-ai/DeepSeek-V3.2, moonshotai/Kimi-K2-Instruct, moonshotai/Kimi-K2-Instruct-0905, moonshotai/Kimi-K2-Thinking, moonshotai/Kimi-K2.5, zai-org/GLM-4.7, zai-org/GLM-4.7-Flash, zai-org/GLM-5, kimi-k2.5, mimo-v2-flash-free, minimax-m2.5, nemotron-3-super-free */
const _obj8 = Type.Object({
maxTokens: Type.Optional(Type.Number()),
headers: Type.Optional(Type.Object({},
{
additionalProperties: Type.String()
 })),
temperature: Type.Optional(Type.Number()),
apiKey: Type.Optional(Type.String()),
transport: Type.Optional(Type.Union([
Type.Literal("sse"),
Type.Literal("websocket"),
Type.Literal("auto")
])),
cacheRetention: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("short"),
Type.Literal("long")
])),
sessionId: Type.Optional(Type.String()),
maxRetryDelayMs: Type.Optional(Type.Number()),
metadata: Type.Optional(Type.Object({},
{
additionalProperties: Type.Unknown()
 })),
toolChoice: Type.Optional(Type.Union([
Type.Literal("auto"),
Type.Literal("none"),
Type.Literal("required"),
Type.Object({
type: Type.Literal("function"),
function: Type.Object({
name: Type.String()
})
})
])),
reasoningEffort: Type.Optional(Type.Union([
Type.Literal("minimal"),
Type.Literal("low"),
Type.Literal("medium"),
Type.Literal("high"),
Type.Literal("xhigh")
]))
});
/** 25 duplicates: codestral-latest, devstral-2512, devstral-medium-2507, devstral-medium-latest, devstral-small-2505, devstral-small-2507, labs-devstral-small-2512, magistral-medium-latest, magistral-small, ministral-3b-latest, ministral-8b-latest, mistral-large-2411, mistral-large-2512, mistral-large-latest, mistral-medium-2505, mistral-medium-2508, mistral-medium-latest, mistral-nemo, mistral-small-2506, mistral-small-latest, open-mistral-7b, open-mixtral-8x22b, open-mixtral-8x7b, pixtral-12b, pixtral-large-latest */
const _obj9 = Type.Object({
maxTokens: Type.Optional(Type.Number()),
headers: Type.Optional(Type.Object({},
{
additionalProperties: Type.String()
 })),
temperature: Type.Optional(Type.Number()),
apiKey: Type.Optional(Type.String()),
transport: Type.Optional(Type.Union([
Type.Literal("sse"),
Type.Literal("websocket"),
Type.Literal("auto")
])),
cacheRetention: Type.Optional(Type.Union([
Type.Literal("none"),
Type.Literal("short"),
Type.Literal("long")
])),
sessionId: Type.Optional(Type.String()),
maxRetryDelayMs: Type.Optional(Type.Number()),
metadata: Type.Optional(Type.Object({},
{
additionalProperties: Type.Unknown()
 })),
toolChoice: Type.Optional(Type.Union([
Type.Literal("auto"),
Type.Literal("none"),
Type.Literal("any"),
Type.Literal("required"),
Type.Object({
type: Type.Literal("function"),
function: Type.Object({
name: Type.String()
})
})
])),
promptMode: Type.Optional(Type.Literal("reasoning"))
});


export type StreamOptionsByProviderAndModel = Static<typeof StreamOptionsByProviderAndModel>
export const StreamOptionsByProviderAndModel = Type.Object({
"amazon-bedrock": Type.Object({
"amazon.nova-2-lite-v1:0": _obj0,
"amazon.nova-lite-v1:0": _obj0,
"amazon.nova-micro-v1:0": _obj0,
"amazon.nova-premier-v1:0": _obj0,
"amazon.nova-pro-v1:0": _obj0,
"anthropic.claude-3-5-haiku-20241022-v1:0": _obj0,
"anthropic.claude-3-5-sonnet-20240620-v1:0": _obj0,
"anthropic.claude-3-5-sonnet-20241022-v2:0": _obj0,
"anthropic.claude-3-7-sonnet-20250219-v1:0": _obj0,
"anthropic.claude-3-haiku-20240307-v1:0": _obj0,
"anthropic.claude-haiku-4-5-20251001-v1:0": _obj0,
"anthropic.claude-opus-4-1-20250805-v1:0": _obj0,
"anthropic.claude-opus-4-20250514-v1:0": _obj0,
"anthropic.claude-opus-4-5-20251101-v1:0": _obj0,
"anthropic.claude-opus-4-6-v1": _obj0,
"anthropic.claude-sonnet-4-20250514-v1:0": _obj0,
"anthropic.claude-sonnet-4-5-20250929-v1:0": _obj0,
"anthropic.claude-sonnet-4-6": _obj0,
"deepseek.r1-v1:0": _obj0,
"deepseek.v3-v1:0": _obj0,
"deepseek.v3.2": _obj0,
"eu.anthropic.claude-haiku-4-5-20251001-v1:0": _obj0,
"eu.anthropic.claude-opus-4-5-20251101-v1:0": _obj0,
"eu.anthropic.claude-opus-4-6-v1": _obj0,
"eu.anthropic.claude-sonnet-4-20250514-v1:0": _obj0,
"eu.anthropic.claude-sonnet-4-5-20250929-v1:0": _obj0,
"eu.anthropic.claude-sonnet-4-6": _obj0,
"global.anthropic.claude-haiku-4-5-20251001-v1:0": _obj0,
"global.anthropic.claude-opus-4-5-20251101-v1:0": _obj0,
"global.anthropic.claude-opus-4-6-v1": _obj0,
"global.anthropic.claude-sonnet-4-20250514-v1:0": _obj0,
"global.anthropic.claude-sonnet-4-5-20250929-v1:0": _obj0,
"global.anthropic.claude-sonnet-4-6": _obj0,
"google.gemma-3-27b-it": _obj0,
"google.gemma-3-4b-it": _obj0,
"meta.llama3-1-405b-instruct-v1:0": _obj0,
"meta.llama3-1-70b-instruct-v1:0": _obj0,
"meta.llama3-1-8b-instruct-v1:0": _obj0,
"meta.llama3-2-11b-instruct-v1:0": _obj0,
"meta.llama3-2-1b-instruct-v1:0": _obj0,
"meta.llama3-2-3b-instruct-v1:0": _obj0,
"meta.llama3-2-90b-instruct-v1:0": _obj0,
"meta.llama3-3-70b-instruct-v1:0": _obj0,
"meta.llama4-maverick-17b-instruct-v1:0": _obj0,
"meta.llama4-scout-17b-instruct-v1:0": _obj0,
"minimax.minimax-m2": _obj0,
"minimax.minimax-m2.1": _obj0,
"mistral.devstral-2-123b": _obj0,
"mistral.magistral-small-2509": _obj0,
"mistral.ministral-3-14b-instruct": _obj0,
"mistral.ministral-3-3b-instruct": _obj0,
"mistral.ministral-3-8b-instruct": _obj0,
"mistral.mistral-large-3-675b-instruct": _obj0,
"mistral.pixtral-large-2502-v1:0": _obj0,
"mistral.voxtral-mini-3b-2507": _obj0,
"mistral.voxtral-small-24b-2507": _obj0,
"moonshot.kimi-k2-thinking": _obj0,
"moonshotai.kimi-k2.5": _obj0,
"nvidia.nemotron-nano-12b-v2": _obj0,
"nvidia.nemotron-nano-3-30b": _obj0,
"nvidia.nemotron-nano-9b-v2": _obj0,
"openai.gpt-oss-120b-1:0": _obj0,
"openai.gpt-oss-20b-1:0": _obj0,
"openai.gpt-oss-safeguard-120b": _obj0,
"openai.gpt-oss-safeguard-20b": _obj0,
"qwen.qwen3-235b-a22b-2507-v1:0": _obj0,
"qwen.qwen3-32b-v1:0": _obj0,
"qwen.qwen3-coder-30b-a3b-v1:0": _obj0,
"qwen.qwen3-coder-480b-a35b-v1:0": _obj0,
"qwen.qwen3-next-80b-a3b": _obj0,
"qwen.qwen3-vl-235b-a22b": _obj0,
"us.anthropic.claude-haiku-4-5-20251001-v1:0": _obj0,
"us.anthropic.claude-opus-4-1-20250805-v1:0": _obj0,
"us.anthropic.claude-opus-4-20250514-v1:0": _obj0,
"us.anthropic.claude-opus-4-5-20251101-v1:0": _obj0,
"us.anthropic.claude-opus-4-6-v1": _obj0,
"us.anthropic.claude-sonnet-4-20250514-v1:0": _obj0,
"us.anthropic.claude-sonnet-4-5-20250929-v1:0": _obj0,
"us.anthropic.claude-sonnet-4-6": _obj0,
"writer.palmyra-x4-v1:0": _obj0,
"writer.palmyra-x5-v1:0": _obj0,
"zai.glm-4.7": _obj0,
"zai.glm-4.7-flash": _obj0
}),
anthropic: Type.Object({
"claude-3-5-haiku-20241022": _obj1,
"claude-3-5-haiku-latest": _obj1,
"claude-3-5-sonnet-20240620": _obj1,
"claude-3-5-sonnet-20241022": _obj1,
"claude-3-7-sonnet-20250219": _obj1,
"claude-3-7-sonnet-latest": _obj1,
"claude-3-haiku-20240307": _obj1,
"claude-3-opus-20240229": _obj1,
"claude-3-sonnet-20240229": _obj1,
"claude-haiku-4-5": _obj1,
"claude-haiku-4-5-20251001": _obj1,
"claude-opus-4-0": _obj1,
"claude-opus-4-1": _obj1,
"claude-opus-4-1-20250805": _obj1,
"claude-opus-4-20250514": _obj1,
"claude-opus-4-5": _obj1,
"claude-opus-4-5-20251101": _obj1,
"claude-opus-4-6": _obj1,
"claude-sonnet-4-0": _obj1,
"claude-sonnet-4-20250514": _obj1,
"claude-sonnet-4-5": _obj1,
"claude-sonnet-4-5-20250929": _obj1,
"claude-sonnet-4-6": _obj1
}),
google: Type.Object({
"gemini-1.5-flash": _obj2,
"gemini-1.5-flash-8b": _obj2,
"gemini-1.5-pro": _obj2,
"gemini-2.0-flash": _obj2,
"gemini-2.0-flash-lite": _obj2,
"gemini-2.5-flash": _obj2,
"gemini-2.5-flash-lite": _obj2,
"gemini-2.5-flash-lite-preview-06-17": _obj2,
"gemini-2.5-flash-lite-preview-09-2025": _obj2,
"gemini-2.5-flash-preview-04-17": _obj2,
"gemini-2.5-flash-preview-05-20": _obj2,
"gemini-2.5-flash-preview-09-2025": _obj2,
"gemini-2.5-pro": _obj2,
"gemini-2.5-pro-preview-05-06": _obj2,
"gemini-2.5-pro-preview-06-05": _obj2,
"gemini-3-flash-preview": _obj2,
"gemini-3-pro-preview": _obj2,
"gemini-3.1-flash-lite-preview": _obj2,
"gemini-3.1-pro-preview": _obj2,
"gemini-3.1-pro-preview-customtools": _obj2,
"gemini-flash-latest": _obj2,
"gemini-flash-lite-latest": _obj2,
"gemini-live-2.5-flash": _obj2,
"gemini-live-2.5-flash-preview-native-audio": _obj2
}),
"google-gemini-cli": Type.Object({
"gemini-2.0-flash": _obj3,
"gemini-2.5-flash": _obj3,
"gemini-2.5-pro": _obj3,
"gemini-3-flash-preview": _obj3,
"gemini-3-pro-preview": _obj3,
"gemini-3.1-pro-preview": _obj3
}),
"google-antigravity": Type.Object({
"claude-sonnet-4-5": _obj3,
"claude-sonnet-4-6": _obj3,
"claude-opus-4-5-thinking": _obj3,
"claude-opus-4-6-thinking": _obj3,
"claude-sonnet-4-5-thinking": _obj3,
"gemini-3-flash": _obj3,
"gemini-3.1-pro-high": _obj3,
"gemini-3.1-pro-low": _obj3,
"gpt-oss-120b-medium": _obj3
}),
"google-vertex": Type.Object({
"gemini-1.5-flash": _obj4,
"gemini-1.5-flash-8b": _obj4,
"gemini-1.5-pro": _obj4,
"gemini-2.0-flash": _obj4,
"gemini-2.0-flash-lite": _obj4,
"gemini-2.5-flash": _obj4,
"gemini-2.5-flash-lite": _obj4,
"gemini-2.5-flash-lite-preview-09-2025": _obj4,
"gemini-2.5-pro": _obj4,
"gemini-3-flash-preview": _obj4,
"gemini-3-pro-preview": _obj4,
"gemini-3.1-pro-preview": _obj4
}),
openai: Type.Object({
"codex-mini-latest": _obj5,
"gpt-4": _obj5,
"gpt-4-turbo": _obj5,
"gpt-4.1": _obj5,
"gpt-4.1-mini": _obj5,
"gpt-4.1-nano": _obj5,
"gpt-4o": _obj5,
"gpt-4o-2024-05-13": _obj5,
"gpt-4o-2024-08-06": _obj5,
"gpt-4o-2024-11-20": _obj5,
"gpt-4o-mini": _obj5,
"gpt-5": _obj5,
"gpt-5-chat-latest": _obj5,
"gpt-5-codex": _obj5,
"gpt-5-mini": _obj5,
"gpt-5-nano": _obj5,
"gpt-5-pro": _obj5,
"gpt-5.1": _obj5,
"gpt-5.1-chat-latest": _obj5,
"gpt-5.1-codex": _obj5,
"gpt-5.1-codex-max": _obj5,
"gpt-5.1-codex-mini": _obj5,
"gpt-5.2": _obj5,
"gpt-5.2-chat-latest": _obj5,
"gpt-5.2-codex": _obj5,
"gpt-5.2-pro": _obj5,
"gpt-5.3-codex": _obj5,
"gpt-5.3-codex-spark": _obj5,
"gpt-5.4": _obj5,
"gpt-5.4-mini": _obj5,
"gpt-5.4-nano": _obj5,
"gpt-5.4-pro": _obj5,
o1: _obj5,
"o1-pro": _obj5,
o3: _obj5,
"o3-deep-research": _obj5,
"o3-mini": _obj5,
"o3-pro": _obj5,
"o4-mini": _obj5,
"o4-mini-deep-research": _obj5
}),
"azure-openai-responses": Type.Object({
"codex-mini-latest": _obj6,
"gpt-4": _obj6,
"gpt-4-turbo": _obj6,
"gpt-4.1": _obj6,
"gpt-4.1-mini": _obj6,
"gpt-4.1-nano": _obj6,
"gpt-4o": _obj6,
"gpt-4o-2024-05-13": _obj6,
"gpt-4o-2024-08-06": _obj6,
"gpt-4o-2024-11-20": _obj6,
"gpt-4o-mini": _obj6,
"gpt-5": _obj6,
"gpt-5-chat-latest": _obj6,
"gpt-5-codex": _obj6,
"gpt-5-mini": _obj6,
"gpt-5-nano": _obj6,
"gpt-5-pro": _obj6,
"gpt-5.1": _obj6,
"gpt-5.1-chat-latest": _obj6,
"gpt-5.1-codex": _obj6,
"gpt-5.1-codex-max": _obj6,
"gpt-5.1-codex-mini": _obj6,
"gpt-5.2": _obj6,
"gpt-5.2-chat-latest": _obj6,
"gpt-5.2-codex": _obj6,
"gpt-5.2-pro": _obj6,
"gpt-5.3-codex": _obj6,
"gpt-5.3-codex-spark": _obj6,
"gpt-5.4": _obj6,
"gpt-5.4-mini": _obj6,
"gpt-5.4-nano": _obj6,
"gpt-5.4-pro": _obj6,
o1: _obj6,
"o1-pro": _obj6,
o3: _obj6,
"o3-deep-research": _obj6,
"o3-mini": _obj6,
"o3-pro": _obj6,
"o4-mini": _obj6,
"o4-mini-deep-research": _obj6
}),
"openai-codex": Type.Object({
"gpt-5.1": _obj7,
"gpt-5.1-codex-max": _obj7,
"gpt-5.1-codex-mini": _obj7,
"gpt-5.2": _obj7,
"gpt-5.2-codex": _obj7,
"gpt-5.3-codex": _obj7,
"gpt-5.3-codex-spark": _obj7,
"gpt-5.4": _obj7
}),
"github-copilot": Type.Object({
"gemini-2.5-pro": _obj8,
"gemini-3-flash-preview": _obj8,
"gemini-3-pro-preview": _obj8,
"gemini-3.1-pro-preview": _obj8,
"gpt-4.1": _obj8,
"gpt-4o": _obj8,
"gpt-5": _obj5,
"gpt-5-mini": _obj5,
"gpt-5.1": _obj5,
"gpt-5.1-codex": _obj5,
"gpt-5.1-codex-max": _obj5,
"gpt-5.1-codex-mini": _obj5,
"gpt-5.2": _obj5,
"gpt-5.2-codex": _obj5,
"gpt-5.3-codex": _obj5,
"gpt-5.4": _obj5,
"gpt-5.4-mini": _obj5,
"gpt-5.4-nano": _obj5,
"claude-haiku-4.5": _obj1,
"claude-opus-4.5": _obj1,
"claude-opus-4.6": _obj1,
"claude-sonnet-4": _obj1,
"claude-sonnet-4.5": _obj1,
"claude-sonnet-4.6": _obj1,
"grok-code-fast-1": _obj8
}),
xai: Type.Object({
"grok-code-fast-1": _obj8,
"grok-2": _obj8,
"grok-2-1212": _obj8,
"grok-2-latest": _obj8,
"grok-2-vision": _obj8,
"grok-2-vision-1212": _obj8,
"grok-2-vision-latest": _obj8,
"grok-3": _obj8,
"grok-3-fast": _obj8,
"grok-3-fast-latest": _obj8,
"grok-3-latest": _obj8,
"grok-3-mini": _obj8,
"grok-3-mini-fast": _obj8,
"grok-3-mini-fast-latest": _obj8,
"grok-3-mini-latest": _obj8,
"grok-4": _obj8,
"grok-4-1-fast": _obj8,
"grok-4-1-fast-non-reasoning": _obj8,
"grok-4-fast": _obj8,
"grok-4-fast-non-reasoning": _obj8,
"grok-4.20-beta-latest-non-reasoning": _obj8,
"grok-4.20-beta-latest-reasoning": _obj8,
"grok-4.20-multi-agent-beta-latest": _obj8,
"grok-beta": _obj8,
"grok-vision-beta": _obj8
}),
groq: Type.Object({
"deepseek-r1-distill-llama-70b": _obj8,
"gemma2-9b-it": _obj8,
"llama-3.1-8b-instant": _obj8,
"llama-3.3-70b-versatile": _obj8,
"llama3-70b-8192": _obj8,
"llama3-8b-8192": _obj8,
"meta-llama/llama-4-maverick-17b-128e-instruct": _obj8,
"meta-llama/llama-4-scout-17b-16e-instruct": _obj8,
"mistral-saba-24b": _obj8,
"moonshotai/kimi-k2-instruct": _obj8,
"moonshotai/kimi-k2-instruct-0905": _obj8,
"openai/gpt-oss-120b": _obj8,
"openai/gpt-oss-20b": _obj8,
"qwen-qwq-32b": _obj8,
"qwen/qwen3-32b": _obj8
}),
cerebras: Type.Object({
"gpt-oss-120b": _obj8,
"llama3.1-8b": _obj8,
"qwen-3-235b-a22b-instruct-2507": _obj8,
"zai-glm-4.7": _obj8
}),
openrouter: Type.Object({
auto: _obj8,
"openai/gpt-oss-120b": _obj8,
"openai/gpt-oss-20b": _obj8,
"qwen/qwen3-32b": _obj8,
"ai21/jamba-large-1.7": _obj8,
"alibaba/tongyi-deepresearch-30b-a3b": _obj8,
"allenai/olmo-3.1-32b-instruct": _obj8,
"amazon/nova-2-lite-v1": _obj8,
"amazon/nova-lite-v1": _obj8,
"amazon/nova-micro-v1": _obj8,
"amazon/nova-premier-v1": _obj8,
"amazon/nova-pro-v1": _obj8,
"anthropic/claude-3-haiku": _obj8,
"anthropic/claude-3.5-haiku": _obj8,
"anthropic/claude-3.5-sonnet": _obj8,
"anthropic/claude-3.7-sonnet": _obj8,
"anthropic/claude-3.7-sonnet:thinking": _obj8,
"anthropic/claude-haiku-4.5": _obj8,
"anthropic/claude-opus-4": _obj8,
"anthropic/claude-opus-4.1": _obj8,
"anthropic/claude-opus-4.5": _obj8,
"anthropic/claude-opus-4.6": _obj8,
"anthropic/claude-sonnet-4": _obj8,
"anthropic/claude-sonnet-4.5": _obj8,
"anthropic/claude-sonnet-4.6": _obj8,
"arcee-ai/trinity-large-preview:free": _obj8,
"arcee-ai/trinity-mini": _obj8,
"arcee-ai/trinity-mini:free": _obj8,
"arcee-ai/virtuoso-large": _obj8,
"baidu/ernie-4.5-21b-a3b": _obj8,
"baidu/ernie-4.5-vl-28b-a3b": _obj8,
"bytedance-seed/seed-1.6": _obj8,
"bytedance-seed/seed-1.6-flash": _obj8,
"bytedance-seed/seed-2.0-lite": _obj8,
"bytedance-seed/seed-2.0-mini": _obj8,
"cohere/command-r-08-2024": _obj8,
"cohere/command-r-plus-08-2024": _obj8,
"deepseek/deepseek-chat": _obj8,
"deepseek/deepseek-chat-v3-0324": _obj8,
"deepseek/deepseek-chat-v3.1": _obj8,
"deepseek/deepseek-r1": _obj8,
"deepseek/deepseek-r1-0528": _obj8,
"deepseek/deepseek-v3.1-terminus": _obj8,
"deepseek/deepseek-v3.2": _obj8,
"deepseek/deepseek-v3.2-exp": _obj8,
"essentialai/rnj-1-instruct": _obj8,
"google/gemini-2.0-flash-001": _obj8,
"google/gemini-2.0-flash-lite-001": _obj8,
"google/gemini-2.5-flash": _obj8,
"google/gemini-2.5-flash-lite": _obj8,
"google/gemini-2.5-flash-lite-preview-09-2025": _obj8,
"google/gemini-2.5-pro": _obj8,
"google/gemini-2.5-pro-preview": _obj8,
"google/gemini-2.5-pro-preview-05-06": _obj8,
"google/gemini-3-flash-preview": _obj8,
"google/gemini-3-pro-preview": _obj8,
"google/gemini-3.1-flash-lite-preview": _obj8,
"google/gemini-3.1-pro-preview": _obj8,
"google/gemini-3.1-pro-preview-customtools": _obj8,
"google/gemma-3-27b-it": _obj8,
"google/gemma-3-27b-it:free": _obj8,
"inception/mercury": _obj8,
"inception/mercury-2": _obj8,
"inception/mercury-coder": _obj8,
"kwaipilot/kat-coder-pro": _obj8,
"meituan/longcat-flash-chat": _obj8,
"meta-llama/llama-3-8b-instruct": _obj8,
"meta-llama/llama-3.1-70b-instruct": _obj8,
"meta-llama/llama-3.1-8b-instruct": _obj8,
"meta-llama/llama-3.3-70b-instruct": _obj8,
"meta-llama/llama-3.3-70b-instruct:free": _obj8,
"meta-llama/llama-4-maverick": _obj8,
"meta-llama/llama-4-scout": _obj8,
"minimax/minimax-m1": _obj8,
"minimax/minimax-m2": _obj8,
"minimax/minimax-m2.1": _obj8,
"minimax/minimax-m2.5": _obj8,
"minimax/minimax-m2.5:free": _obj8,
"mistralai/codestral-2508": _obj8,
"mistralai/devstral-2512": _obj8,
"mistralai/devstral-medium": _obj8,
"mistralai/devstral-small": _obj8,
"mistralai/ministral-14b-2512": _obj8,
"mistralai/ministral-3b-2512": _obj8,
"mistralai/ministral-8b-2512": _obj8,
"mistralai/mistral-large": _obj8,
"mistralai/mistral-large-2407": _obj8,
"mistralai/mistral-large-2411": _obj8,
"mistralai/mistral-large-2512": _obj8,
"mistralai/mistral-medium-3": _obj8,
"mistralai/mistral-medium-3.1": _obj8,
"mistralai/mistral-nemo": _obj8,
"mistralai/mistral-saba": _obj8,
"mistralai/mistral-small-24b-instruct-2501": _obj8,
"mistralai/mistral-small-2603": _obj8,
"mistralai/mistral-small-3.1-24b-instruct:free": _obj8,
"mistralai/mistral-small-3.2-24b-instruct": _obj8,
"mistralai/mistral-small-creative": _obj8,
"mistralai/mixtral-8x22b-instruct": _obj8,
"mistralai/mixtral-8x7b-instruct": _obj8,
"mistralai/pixtral-large-2411": _obj8,
"mistralai/voxtral-small-24b-2507": _obj8,
"moonshotai/kimi-k2": _obj8,
"moonshotai/kimi-k2-0905": _obj8,
"moonshotai/kimi-k2-thinking": _obj8,
"moonshotai/kimi-k2.5": _obj8,
"nex-agi/deepseek-v3.1-nex-n1": _obj8,
"nvidia/llama-3.1-nemotron-70b-instruct": _obj8,
"nvidia/llama-3.3-nemotron-super-49b-v1.5": _obj8,
"nvidia/nemotron-3-nano-30b-a3b": _obj8,
"nvidia/nemotron-3-nano-30b-a3b:free": _obj8,
"nvidia/nemotron-3-super-120b-a12b:free": _obj8,
"nvidia/nemotron-nano-12b-v2-vl:free": _obj8,
"nvidia/nemotron-nano-9b-v2": _obj8,
"nvidia/nemotron-nano-9b-v2:free": _obj8,
"openai/gpt-3.5-turbo": _obj8,
"openai/gpt-3.5-turbo-0613": _obj8,
"openai/gpt-3.5-turbo-16k": _obj8,
"openai/gpt-4": _obj8,
"openai/gpt-4-0314": _obj8,
"openai/gpt-4-1106-preview": _obj8,
"openai/gpt-4-turbo": _obj8,
"openai/gpt-4-turbo-preview": _obj8,
"openai/gpt-4.1": _obj8,
"openai/gpt-4.1-mini": _obj8,
"openai/gpt-4.1-nano": _obj8,
"openai/gpt-4o": _obj8,
"openai/gpt-4o-2024-05-13": _obj8,
"openai/gpt-4o-2024-08-06": _obj8,
"openai/gpt-4o-2024-11-20": _obj8,
"openai/gpt-4o-audio-preview": _obj8,
"openai/gpt-4o-mini": _obj8,
"openai/gpt-4o-mini-2024-07-18": _obj8,
"openai/gpt-4o:extended": _obj8,
"openai/gpt-5": _obj8,
"openai/gpt-5-codex": _obj8,
"openai/gpt-5-image": _obj8,
"openai/gpt-5-image-mini": _obj8,
"openai/gpt-5-mini": _obj8,
"openai/gpt-5-nano": _obj8,
"openai/gpt-5-pro": _obj8,
"openai/gpt-5.1": _obj8,
"openai/gpt-5.1-chat": _obj8,
"openai/gpt-5.1-codex": _obj8,
"openai/gpt-5.1-codex-max": _obj8,
"openai/gpt-5.1-codex-mini": _obj8,
"openai/gpt-5.2": _obj8,
"openai/gpt-5.2-chat": _obj8,
"openai/gpt-5.2-codex": _obj8,
"openai/gpt-5.2-pro": _obj8,
"openai/gpt-5.3-chat": _obj8,
"openai/gpt-5.3-codex": _obj8,
"openai/gpt-5.4": _obj8,
"openai/gpt-5.4-mini": _obj8,
"openai/gpt-5.4-nano": _obj8,
"openai/gpt-5.4-pro": _obj8,
"openai/gpt-oss-120b:free": _obj8,
"openai/gpt-oss-20b:free": _obj8,
"openai/gpt-oss-safeguard-20b": _obj8,
"openai/o1": _obj8,
"openai/o3": _obj8,
"openai/o3-deep-research": _obj8,
"openai/o3-mini": _obj8,
"openai/o3-mini-high": _obj8,
"openai/o3-pro": _obj8,
"openai/o4-mini": _obj8,
"openai/o4-mini-deep-research": _obj8,
"openai/o4-mini-high": _obj8,
"openrouter/auto": _obj8,
"openrouter/free": _obj8,
"openrouter/healer-alpha": _obj8,
"openrouter/hunter-alpha": _obj8,
"prime-intellect/intellect-3": _obj8,
"qwen/qwen-2.5-72b-instruct": _obj8,
"qwen/qwen-2.5-7b-instruct": _obj8,
"qwen/qwen-max": _obj8,
"qwen/qwen-plus": _obj8,
"qwen/qwen-plus-2025-07-28": _obj8,
"qwen/qwen-plus-2025-07-28:thinking": _obj8,
"qwen/qwen-turbo": _obj8,
"qwen/qwen-vl-max": _obj8,
"qwen/qwen3-14b": _obj8,
"qwen/qwen3-235b-a22b": _obj8,
"qwen/qwen3-235b-a22b-2507": _obj8,
"qwen/qwen3-235b-a22b-thinking-2507": _obj8,
"qwen/qwen3-30b-a3b": _obj8,
"qwen/qwen3-30b-a3b-instruct-2507": _obj8,
"qwen/qwen3-30b-a3b-thinking-2507": _obj8,
"qwen/qwen3-4b:free": _obj8,
"qwen/qwen3-8b": _obj8,
"qwen/qwen3-coder": _obj8,
"qwen/qwen3-coder-30b-a3b-instruct": _obj8,
"qwen/qwen3-coder-flash": _obj8,
"qwen/qwen3-coder-next": _obj8,
"qwen/qwen3-coder-plus": _obj8,
"qwen/qwen3-coder:free": _obj8,
"qwen/qwen3-max": _obj8,
"qwen/qwen3-max-thinking": _obj8,
"qwen/qwen3-next-80b-a3b-instruct": _obj8,
"qwen/qwen3-next-80b-a3b-instruct:free": _obj8,
"qwen/qwen3-next-80b-a3b-thinking": _obj8,
"qwen/qwen3-vl-235b-a22b-instruct": _obj8,
"qwen/qwen3-vl-235b-a22b-thinking": _obj8,
"qwen/qwen3-vl-30b-a3b-instruct": _obj8,
"qwen/qwen3-vl-30b-a3b-thinking": _obj8,
"qwen/qwen3-vl-32b-instruct": _obj8,
"qwen/qwen3-vl-8b-instruct": _obj8,
"qwen/qwen3-vl-8b-thinking": _obj8,
"qwen/qwen3.5-122b-a10b": _obj8,
"qwen/qwen3.5-27b": _obj8,
"qwen/qwen3.5-35b-a3b": _obj8,
"qwen/qwen3.5-397b-a17b": _obj8,
"qwen/qwen3.5-9b": _obj8,
"qwen/qwen3.5-flash-02-23": _obj8,
"qwen/qwen3.5-plus-02-15": _obj8,
"qwen/qwq-32b": _obj8,
"relace/relace-search": _obj8,
"sao10k/l3-euryale-70b": _obj8,
"sao10k/l3.1-euryale-70b": _obj8,
"stepfun/step-3.5-flash": _obj8,
"stepfun/step-3.5-flash:free": _obj8,
"thedrummer/rocinante-12b": _obj8,
"thedrummer/unslopnemo-12b": _obj8,
"tngtech/deepseek-r1t2-chimera": _obj8,
"upstage/solar-pro-3": _obj8,
"x-ai/grok-3": _obj8,
"x-ai/grok-3-beta": _obj8,
"x-ai/grok-3-mini": _obj8,
"x-ai/grok-3-mini-beta": _obj8,
"x-ai/grok-4": _obj8,
"x-ai/grok-4-fast": _obj8,
"x-ai/grok-4.1-fast": _obj8,
"x-ai/grok-4.20-beta": _obj8,
"x-ai/grok-code-fast-1": _obj8,
"xiaomi/mimo-v2-flash": _obj8,
"z-ai/glm-4-32b": _obj8,
"z-ai/glm-4.5": _obj8,
"z-ai/glm-4.5-air": _obj8,
"z-ai/glm-4.5-air:free": _obj8,
"z-ai/glm-4.5v": _obj8,
"z-ai/glm-4.6": _obj8,
"z-ai/glm-4.6v": _obj8,
"z-ai/glm-4.7": _obj8,
"z-ai/glm-4.7-flash": _obj8,
"z-ai/glm-5": _obj8,
"z-ai/glm-5-turbo": _obj8
}),
"vercel-ai-gateway": Type.Object({
"openai/gpt-oss-20b": _obj1,
"anthropic/claude-3-haiku": _obj1,
"anthropic/claude-3.5-haiku": _obj1,
"anthropic/claude-3.5-sonnet": _obj1,
"anthropic/claude-3.7-sonnet": _obj1,
"anthropic/claude-haiku-4.5": _obj1,
"anthropic/claude-opus-4": _obj1,
"anthropic/claude-opus-4.1": _obj1,
"anthropic/claude-opus-4.5": _obj1,
"anthropic/claude-opus-4.6": _obj1,
"anthropic/claude-sonnet-4": _obj1,
"anthropic/claude-sonnet-4.5": _obj1,
"anthropic/claude-sonnet-4.6": _obj1,
"deepseek/deepseek-r1": _obj1,
"deepseek/deepseek-v3.1-terminus": _obj1,
"deepseek/deepseek-v3.2": _obj1,
"google/gemini-2.5-flash": _obj1,
"google/gemini-2.5-flash-lite": _obj1,
"google/gemini-2.5-pro": _obj1,
"google/gemini-3-pro-preview": _obj1,
"google/gemini-3.1-flash-lite-preview": _obj1,
"google/gemini-3.1-pro-preview": _obj1,
"inception/mercury-2": _obj1,
"meituan/longcat-flash-chat": _obj1,
"minimax/minimax-m2": _obj1,
"minimax/minimax-m2.1": _obj1,
"minimax/minimax-m2.5": _obj1,
"moonshotai/kimi-k2": _obj1,
"moonshotai/kimi-k2-0905": _obj1,
"moonshotai/kimi-k2-thinking": _obj1,
"moonshotai/kimi-k2.5": _obj1,
"nvidia/nemotron-nano-9b-v2": _obj1,
"openai/gpt-4-turbo": _obj1,
"openai/gpt-4.1": _obj1,
"openai/gpt-4.1-mini": _obj1,
"openai/gpt-4.1-nano": _obj1,
"openai/gpt-4o": _obj1,
"openai/gpt-4o-mini": _obj1,
"openai/gpt-5": _obj1,
"openai/gpt-5-codex": _obj1,
"openai/gpt-5-mini": _obj1,
"openai/gpt-5-nano": _obj1,
"openai/gpt-5-pro": _obj1,
"openai/gpt-5.1-codex": _obj1,
"openai/gpt-5.1-codex-max": _obj1,
"openai/gpt-5.1-codex-mini": _obj1,
"openai/gpt-5.2": _obj1,
"openai/gpt-5.2-chat": _obj1,
"openai/gpt-5.2-codex": _obj1,
"openai/gpt-5.2-pro": _obj1,
"openai/gpt-5.3-chat": _obj1,
"openai/gpt-5.3-codex": _obj1,
"openai/gpt-5.4": _obj1,
"openai/gpt-5.4-mini": _obj1,
"openai/gpt-5.4-nano": _obj1,
"openai/gpt-5.4-pro": _obj1,
"openai/gpt-oss-safeguard-20b": _obj1,
"openai/o1": _obj1,
"openai/o3": _obj1,
"openai/o3-deep-research": _obj1,
"openai/o3-mini": _obj1,
"openai/o3-pro": _obj1,
"openai/o4-mini": _obj1,
"prime-intellect/intellect-3": _obj1,
"xiaomi/mimo-v2-flash": _obj1,
"alibaba/qwen-3-14b": _obj1,
"alibaba/qwen-3-235b": _obj1,
"alibaba/qwen-3-30b": _obj1,
"alibaba/qwen-3-32b": _obj1,
"alibaba/qwen3-235b-a22b-thinking": _obj1,
"alibaba/qwen3-coder": _obj1,
"alibaba/qwen3-coder-30b-a3b": _obj1,
"alibaba/qwen3-coder-next": _obj1,
"alibaba/qwen3-coder-plus": _obj1,
"alibaba/qwen3-max": _obj1,
"alibaba/qwen3-max-preview": _obj1,
"alibaba/qwen3-max-thinking": _obj1,
"alibaba/qwen3-vl-thinking": _obj1,
"alibaba/qwen3.5-flash": _obj1,
"alibaba/qwen3.5-plus": _obj1,
"anthropic/claude-3.5-sonnet-20240620": _obj1,
"arcee-ai/trinity-large-preview": _obj1,
"bytedance/seed-1.6": _obj1,
"cohere/command-a": _obj1,
"deepseek/deepseek-v3": _obj1,
"deepseek/deepseek-v3.1": _obj1,
"deepseek/deepseek-v3.2-thinking": _obj1,
"google/gemini-2.0-flash": _obj1,
"google/gemini-2.0-flash-lite": _obj1,
"google/gemini-3-flash": _obj1,
"inception/mercury-coder-small": _obj1,
"meituan/longcat-flash-thinking": _obj1,
"meta/llama-3.1-70b": _obj1,
"meta/llama-3.1-8b": _obj1,
"meta/llama-3.2-11b": _obj1,
"meta/llama-3.2-90b": _obj1,
"meta/llama-3.3-70b": _obj1,
"meta/llama-4-maverick": _obj1,
"meta/llama-4-scout": _obj1,
"minimax/minimax-m2.1-lightning": _obj1,
"minimax/minimax-m2.5-highspeed": _obj1,
"mistral/codestral": _obj1,
"mistral/devstral-2": _obj1,
"mistral/devstral-small": _obj1,
"mistral/devstral-small-2": _obj1,
"mistral/ministral-3b": _obj1,
"mistral/ministral-8b": _obj1,
"mistral/mistral-medium": _obj1,
"mistral/mistral-small": _obj1,
"mistral/pixtral-12b": _obj1,
"mistral/pixtral-large": _obj1,
"moonshotai/kimi-k2-thinking-turbo": _obj1,
"moonshotai/kimi-k2-turbo": _obj1,
"nvidia/nemotron-nano-12b-v2-vl": _obj1,
"openai/gpt-5-chat": _obj1,
"openai/gpt-5.1-instant": _obj1,
"openai/gpt-5.1-thinking": _obj1,
"perplexity/sonar": _obj1,
"perplexity/sonar-pro": _obj1,
"xai/grok-2-vision": _obj1,
"xai/grok-3": _obj1,
"xai/grok-3-fast": _obj1,
"xai/grok-3-mini": _obj1,
"xai/grok-3-mini-fast": _obj1,
"xai/grok-4": _obj1,
"xai/grok-4-fast-non-reasoning": _obj1,
"xai/grok-4-fast-reasoning": _obj1,
"xai/grok-4.1-fast-non-reasoning": _obj1,
"xai/grok-4.1-fast-reasoning": _obj1,
"xai/grok-4.20-multi-agent-beta": _obj1,
"xai/grok-4.20-non-reasoning-beta": _obj1,
"xai/grok-4.20-reasoning-beta": _obj1,
"xai/grok-code-fast-1": _obj1,
"zai/glm-4.5": _obj1,
"zai/glm-4.5-air": _obj1,
"zai/glm-4.5v": _obj1,
"zai/glm-4.6": _obj1,
"zai/glm-4.6v": _obj1,
"zai/glm-4.6v-flash": _obj1,
"zai/glm-4.7": _obj1,
"zai/glm-4.7-flash": _obj1,
"zai/glm-4.7-flashx": _obj1,
"zai/glm-5": _obj1,
"zai/glm-5-turbo": _obj1
}),
zai: Type.Object({
"glm-4.5": _obj8,
"glm-4.5-air": _obj8,
"glm-4.5-flash": _obj8,
"glm-4.5v": _obj8,
"glm-4.6": _obj8,
"glm-4.6v": _obj8,
"glm-4.7": _obj8,
"glm-4.7-flash": _obj8,
"glm-5": _obj8,
"glm-5-turbo": _obj8
}),
mistral: Type.Object({
"codestral-latest": _obj9,
"devstral-2512": _obj9,
"devstral-medium-2507": _obj9,
"devstral-medium-latest": _obj9,
"devstral-small-2505": _obj9,
"devstral-small-2507": _obj9,
"labs-devstral-small-2512": _obj9,
"magistral-medium-latest": _obj9,
"magistral-small": _obj9,
"ministral-3b-latest": _obj9,
"ministral-8b-latest": _obj9,
"mistral-large-2411": _obj9,
"mistral-large-2512": _obj9,
"mistral-large-latest": _obj9,
"mistral-medium-2505": _obj9,
"mistral-medium-2508": _obj9,
"mistral-medium-latest": _obj9,
"mistral-nemo": _obj9,
"mistral-small-2506": _obj9,
"mistral-small-latest": _obj9,
"open-mistral-7b": _obj9,
"open-mixtral-8x22b": _obj9,
"open-mixtral-8x7b": _obj9,
"pixtral-12b": _obj9,
"pixtral-large-latest": _obj9
}),
minimax: Type.Object({
"MiniMax-M2": _obj1,
"MiniMax-M2.1": _obj1,
"MiniMax-M2.5": _obj1,
"MiniMax-M2.5-highspeed": _obj1
}),
"minimax-cn": Type.Object({
"MiniMax-M2": _obj1,
"MiniMax-M2.1": _obj1,
"MiniMax-M2.5": _obj1,
"MiniMax-M2.5-highspeed": _obj1
}),
huggingface: Type.Object({
"MiniMaxAI/MiniMax-M2.1": _obj8,
"MiniMaxAI/MiniMax-M2.5": _obj8,
"Qwen/Qwen3-235B-A22B-Thinking-2507": _obj8,
"Qwen/Qwen3-Coder-480B-A35B-Instruct": _obj8,
"Qwen/Qwen3-Coder-Next": _obj8,
"Qwen/Qwen3-Next-80B-A3B-Instruct": _obj8,
"Qwen/Qwen3-Next-80B-A3B-Thinking": _obj8,
"Qwen/Qwen3.5-397B-A17B": _obj8,
"XiaomiMiMo/MiMo-V2-Flash": _obj8,
"deepseek-ai/DeepSeek-R1-0528": _obj8,
"deepseek-ai/DeepSeek-V3.2": _obj8,
"moonshotai/Kimi-K2-Instruct": _obj8,
"moonshotai/Kimi-K2-Instruct-0905": _obj8,
"moonshotai/Kimi-K2-Thinking": _obj8,
"moonshotai/Kimi-K2.5": _obj8,
"zai-org/GLM-4.7": _obj8,
"zai-org/GLM-4.7-Flash": _obj8,
"zai-org/GLM-5": _obj8
}),
opencode: Type.Object({
"claude-haiku-4-5": _obj1,
"claude-opus-4-1": _obj1,
"claude-opus-4-5": _obj1,
"claude-opus-4-6": _obj1,
"claude-sonnet-4-5": _obj1,
"claude-sonnet-4-6": _obj1,
"gemini-3-flash": _obj2,
"gpt-5": _obj5,
"gpt-5-codex": _obj5,
"gpt-5-nano": _obj5,
"gpt-5.1": _obj5,
"gpt-5.1-codex": _obj5,
"gpt-5.1-codex-max": _obj5,
"gpt-5.1-codex-mini": _obj5,
"gpt-5.2": _obj5,
"gpt-5.2-codex": _obj5,
"gpt-5.3-codex": _obj5,
"gpt-5.4": _obj5,
"gpt-5.4-pro": _obj5,
"claude-sonnet-4": _obj1,
"glm-5": _obj8,
"big-pickle": _obj1,
"claude-3-5-haiku": _obj1,
"gemini-3.1-pro": _obj2,
"kimi-k2.5": _obj8,
"mimo-v2-flash-free": _obj8,
"minimax-m2.5": _obj8,
"minimax-m2.5-free": _obj1,
"nemotron-3-super-free": _obj8
}),
"opencode-go": Type.Object({
"glm-5": _obj8,
"kimi-k2.5": _obj8,
"minimax-m2.5": _obj1
}),
"kimi-coding": Type.Object({
k2p5: _obj1,
"kimi-k2-thinking": _obj1
})
})

const _lit0 = Type.Literal("stream");
const _lit1 = Type.Literal("streamAnthropic");
const _lit2 = Type.Literal("streamGoogle");
const _lit3 = Type.Literal("streamGoogleGeminiCli");
const _lit4 = Type.Literal("streamGoogleVertex");
const _lit5 = Type.Literal("streamOpenAIResponses");
const _lit6 = Type.Literal("streamAzureOpenAIResponses");
const _lit7 = Type.Literal("streamOpenAICodexResponses");
const _lit8 = Type.Literal("streamOpenAICompletions");
const _lit9 = Type.Literal("streamMistral");


export type StreamFunctionByProviderAndModel = Static<typeof StreamFunctionByProviderAndModel>
export const StreamFunctionByProviderAndModel = Type.Object({
"amazon-bedrock": Type.Object({
"amazon.nova-2-lite-v1:0": _lit0,
"amazon.nova-lite-v1:0": _lit0,
"amazon.nova-micro-v1:0": _lit0,
"amazon.nova-premier-v1:0": _lit0,
"amazon.nova-pro-v1:0": _lit0,
"anthropic.claude-3-5-haiku-20241022-v1:0": _lit0,
"anthropic.claude-3-5-sonnet-20240620-v1:0": _lit0,
"anthropic.claude-3-5-sonnet-20241022-v2:0": _lit0,
"anthropic.claude-3-7-sonnet-20250219-v1:0": _lit0,
"anthropic.claude-3-haiku-20240307-v1:0": _lit0,
"anthropic.claude-haiku-4-5-20251001-v1:0": _lit0,
"anthropic.claude-opus-4-1-20250805-v1:0": _lit0,
"anthropic.claude-opus-4-20250514-v1:0": _lit0,
"anthropic.claude-opus-4-5-20251101-v1:0": _lit0,
"anthropic.claude-opus-4-6-v1": _lit0,
"anthropic.claude-sonnet-4-20250514-v1:0": _lit0,
"anthropic.claude-sonnet-4-5-20250929-v1:0": _lit0,
"anthropic.claude-sonnet-4-6": _lit0,
"deepseek.r1-v1:0": _lit0,
"deepseek.v3-v1:0": _lit0,
"deepseek.v3.2": _lit0,
"eu.anthropic.claude-haiku-4-5-20251001-v1:0": _lit0,
"eu.anthropic.claude-opus-4-5-20251101-v1:0": _lit0,
"eu.anthropic.claude-opus-4-6-v1": _lit0,
"eu.anthropic.claude-sonnet-4-20250514-v1:0": _lit0,
"eu.anthropic.claude-sonnet-4-5-20250929-v1:0": _lit0,
"eu.anthropic.claude-sonnet-4-6": _lit0,
"global.anthropic.claude-haiku-4-5-20251001-v1:0": _lit0,
"global.anthropic.claude-opus-4-5-20251101-v1:0": _lit0,
"global.anthropic.claude-opus-4-6-v1": _lit0,
"global.anthropic.claude-sonnet-4-20250514-v1:0": _lit0,
"global.anthropic.claude-sonnet-4-5-20250929-v1:0": _lit0,
"global.anthropic.claude-sonnet-4-6": _lit0,
"google.gemma-3-27b-it": _lit0,
"google.gemma-3-4b-it": _lit0,
"meta.llama3-1-405b-instruct-v1:0": _lit0,
"meta.llama3-1-70b-instruct-v1:0": _lit0,
"meta.llama3-1-8b-instruct-v1:0": _lit0,
"meta.llama3-2-11b-instruct-v1:0": _lit0,
"meta.llama3-2-1b-instruct-v1:0": _lit0,
"meta.llama3-2-3b-instruct-v1:0": _lit0,
"meta.llama3-2-90b-instruct-v1:0": _lit0,
"meta.llama3-3-70b-instruct-v1:0": _lit0,
"meta.llama4-maverick-17b-instruct-v1:0": _lit0,
"meta.llama4-scout-17b-instruct-v1:0": _lit0,
"minimax.minimax-m2": _lit0,
"minimax.minimax-m2.1": _lit0,
"mistral.devstral-2-123b": _lit0,
"mistral.magistral-small-2509": _lit0,
"mistral.ministral-3-14b-instruct": _lit0,
"mistral.ministral-3-3b-instruct": _lit0,
"mistral.ministral-3-8b-instruct": _lit0,
"mistral.mistral-large-3-675b-instruct": _lit0,
"mistral.pixtral-large-2502-v1:0": _lit0,
"mistral.voxtral-mini-3b-2507": _lit0,
"mistral.voxtral-small-24b-2507": _lit0,
"moonshot.kimi-k2-thinking": _lit0,
"moonshotai.kimi-k2.5": _lit0,
"nvidia.nemotron-nano-12b-v2": _lit0,
"nvidia.nemotron-nano-3-30b": _lit0,
"nvidia.nemotron-nano-9b-v2": _lit0,
"openai.gpt-oss-120b-1:0": _lit0,
"openai.gpt-oss-20b-1:0": _lit0,
"openai.gpt-oss-safeguard-120b": _lit0,
"openai.gpt-oss-safeguard-20b": _lit0,
"qwen.qwen3-235b-a22b-2507-v1:0": _lit0,
"qwen.qwen3-32b-v1:0": _lit0,
"qwen.qwen3-coder-30b-a3b-v1:0": _lit0,
"qwen.qwen3-coder-480b-a35b-v1:0": _lit0,
"qwen.qwen3-next-80b-a3b": _lit0,
"qwen.qwen3-vl-235b-a22b": _lit0,
"us.anthropic.claude-haiku-4-5-20251001-v1:0": _lit0,
"us.anthropic.claude-opus-4-1-20250805-v1:0": _lit0,
"us.anthropic.claude-opus-4-20250514-v1:0": _lit0,
"us.anthropic.claude-opus-4-5-20251101-v1:0": _lit0,
"us.anthropic.claude-opus-4-6-v1": _lit0,
"us.anthropic.claude-sonnet-4-20250514-v1:0": _lit0,
"us.anthropic.claude-sonnet-4-5-20250929-v1:0": _lit0,
"us.anthropic.claude-sonnet-4-6": _lit0,
"writer.palmyra-x4-v1:0": _lit0,
"writer.palmyra-x5-v1:0": _lit0,
"zai.glm-4.7": _lit0,
"zai.glm-4.7-flash": _lit0
}),
anthropic: Type.Object({
"claude-3-5-haiku-20241022": _lit1,
"claude-3-5-haiku-latest": _lit1,
"claude-3-5-sonnet-20240620": _lit1,
"claude-3-5-sonnet-20241022": _lit1,
"claude-3-7-sonnet-20250219": _lit1,
"claude-3-7-sonnet-latest": _lit1,
"claude-3-haiku-20240307": _lit1,
"claude-3-opus-20240229": _lit1,
"claude-3-sonnet-20240229": _lit1,
"claude-haiku-4-5": _lit1,
"claude-haiku-4-5-20251001": _lit1,
"claude-opus-4-0": _lit1,
"claude-opus-4-1": _lit1,
"claude-opus-4-1-20250805": _lit1,
"claude-opus-4-20250514": _lit1,
"claude-opus-4-5": _lit1,
"claude-opus-4-5-20251101": _lit1,
"claude-opus-4-6": _lit1,
"claude-sonnet-4-0": _lit1,
"claude-sonnet-4-20250514": _lit1,
"claude-sonnet-4-5": _lit1,
"claude-sonnet-4-5-20250929": _lit1,
"claude-sonnet-4-6": _lit1
}),
google: Type.Object({
"gemini-1.5-flash": _lit2,
"gemini-1.5-flash-8b": _lit2,
"gemini-1.5-pro": _lit2,
"gemini-2.0-flash": _lit2,
"gemini-2.0-flash-lite": _lit2,
"gemini-2.5-flash": _lit2,
"gemini-2.5-flash-lite": _lit2,
"gemini-2.5-flash-lite-preview-06-17": _lit2,
"gemini-2.5-flash-lite-preview-09-2025": _lit2,
"gemini-2.5-flash-preview-04-17": _lit2,
"gemini-2.5-flash-preview-05-20": _lit2,
"gemini-2.5-flash-preview-09-2025": _lit2,
"gemini-2.5-pro": _lit2,
"gemini-2.5-pro-preview-05-06": _lit2,
"gemini-2.5-pro-preview-06-05": _lit2,
"gemini-3-flash-preview": _lit2,
"gemini-3-pro-preview": _lit2,
"gemini-3.1-flash-lite-preview": _lit2,
"gemini-3.1-pro-preview": _lit2,
"gemini-3.1-pro-preview-customtools": _lit2,
"gemini-flash-latest": _lit2,
"gemini-flash-lite-latest": _lit2,
"gemini-live-2.5-flash": _lit2,
"gemini-live-2.5-flash-preview-native-audio": _lit2
}),
"google-gemini-cli": Type.Object({
"gemini-2.0-flash": _lit3,
"gemini-2.5-flash": _lit3,
"gemini-2.5-pro": _lit3,
"gemini-3-flash-preview": _lit3,
"gemini-3-pro-preview": _lit3,
"gemini-3.1-pro-preview": _lit3
}),
"google-antigravity": Type.Object({
"claude-sonnet-4-5": _lit3,
"claude-sonnet-4-6": _lit3,
"claude-opus-4-5-thinking": _lit3,
"claude-opus-4-6-thinking": _lit3,
"claude-sonnet-4-5-thinking": _lit3,
"gemini-3-flash": _lit3,
"gemini-3.1-pro-high": _lit3,
"gemini-3.1-pro-low": _lit3,
"gpt-oss-120b-medium": _lit3
}),
"google-vertex": Type.Object({
"gemini-1.5-flash": _lit4,
"gemini-1.5-flash-8b": _lit4,
"gemini-1.5-pro": _lit4,
"gemini-2.0-flash": _lit4,
"gemini-2.0-flash-lite": _lit4,
"gemini-2.5-flash": _lit4,
"gemini-2.5-flash-lite": _lit4,
"gemini-2.5-flash-lite-preview-09-2025": _lit4,
"gemini-2.5-pro": _lit4,
"gemini-3-flash-preview": _lit4,
"gemini-3-pro-preview": _lit4,
"gemini-3.1-pro-preview": _lit4
}),
openai: Type.Object({
"codex-mini-latest": _lit5,
"gpt-4": _lit5,
"gpt-4-turbo": _lit5,
"gpt-4.1": _lit5,
"gpt-4.1-mini": _lit5,
"gpt-4.1-nano": _lit5,
"gpt-4o": _lit5,
"gpt-4o-2024-05-13": _lit5,
"gpt-4o-2024-08-06": _lit5,
"gpt-4o-2024-11-20": _lit5,
"gpt-4o-mini": _lit5,
"gpt-5": _lit5,
"gpt-5-chat-latest": _lit5,
"gpt-5-codex": _lit5,
"gpt-5-mini": _lit5,
"gpt-5-nano": _lit5,
"gpt-5-pro": _lit5,
"gpt-5.1": _lit5,
"gpt-5.1-chat-latest": _lit5,
"gpt-5.1-codex": _lit5,
"gpt-5.1-codex-max": _lit5,
"gpt-5.1-codex-mini": _lit5,
"gpt-5.2": _lit5,
"gpt-5.2-chat-latest": _lit5,
"gpt-5.2-codex": _lit5,
"gpt-5.2-pro": _lit5,
"gpt-5.3-codex": _lit5,
"gpt-5.3-codex-spark": _lit5,
"gpt-5.4": _lit5,
"gpt-5.4-mini": _lit5,
"gpt-5.4-nano": _lit5,
"gpt-5.4-pro": _lit5,
o1: _lit5,
"o1-pro": _lit5,
o3: _lit5,
"o3-deep-research": _lit5,
"o3-mini": _lit5,
"o3-pro": _lit5,
"o4-mini": _lit5,
"o4-mini-deep-research": _lit5
}),
"azure-openai-responses": Type.Object({
"codex-mini-latest": _lit6,
"gpt-4": _lit6,
"gpt-4-turbo": _lit6,
"gpt-4.1": _lit6,
"gpt-4.1-mini": _lit6,
"gpt-4.1-nano": _lit6,
"gpt-4o": _lit6,
"gpt-4o-2024-05-13": _lit6,
"gpt-4o-2024-08-06": _lit6,
"gpt-4o-2024-11-20": _lit6,
"gpt-4o-mini": _lit6,
"gpt-5": _lit6,
"gpt-5-chat-latest": _lit6,
"gpt-5-codex": _lit6,
"gpt-5-mini": _lit6,
"gpt-5-nano": _lit6,
"gpt-5-pro": _lit6,
"gpt-5.1": _lit6,
"gpt-5.1-chat-latest": _lit6,
"gpt-5.1-codex": _lit6,
"gpt-5.1-codex-max": _lit6,
"gpt-5.1-codex-mini": _lit6,
"gpt-5.2": _lit6,
"gpt-5.2-chat-latest": _lit6,
"gpt-5.2-codex": _lit6,
"gpt-5.2-pro": _lit6,
"gpt-5.3-codex": _lit6,
"gpt-5.3-codex-spark": _lit6,
"gpt-5.4": _lit6,
"gpt-5.4-mini": _lit6,
"gpt-5.4-nano": _lit6,
"gpt-5.4-pro": _lit6,
o1: _lit6,
"o1-pro": _lit6,
o3: _lit6,
"o3-deep-research": _lit6,
"o3-mini": _lit6,
"o3-pro": _lit6,
"o4-mini": _lit6,
"o4-mini-deep-research": _lit6
}),
"openai-codex": Type.Object({
"gpt-5.1": _lit7,
"gpt-5.1-codex-max": _lit7,
"gpt-5.1-codex-mini": _lit7,
"gpt-5.2": _lit7,
"gpt-5.2-codex": _lit7,
"gpt-5.3-codex": _lit7,
"gpt-5.3-codex-spark": _lit7,
"gpt-5.4": _lit7
}),
"github-copilot": Type.Object({
"gemini-2.5-pro": _lit8,
"gemini-3-flash-preview": _lit8,
"gemini-3-pro-preview": _lit8,
"gemini-3.1-pro-preview": _lit8,
"gpt-4.1": _lit8,
"gpt-4o": _lit8,
"gpt-5": _lit5,
"gpt-5-mini": _lit5,
"gpt-5.1": _lit5,
"gpt-5.1-codex": _lit5,
"gpt-5.1-codex-max": _lit5,
"gpt-5.1-codex-mini": _lit5,
"gpt-5.2": _lit5,
"gpt-5.2-codex": _lit5,
"gpt-5.3-codex": _lit5,
"gpt-5.4": _lit5,
"gpt-5.4-mini": _lit5,
"gpt-5.4-nano": _lit5,
"claude-haiku-4.5": _lit1,
"claude-opus-4.5": _lit1,
"claude-opus-4.6": _lit1,
"claude-sonnet-4": _lit1,
"claude-sonnet-4.5": _lit1,
"claude-sonnet-4.6": _lit1,
"grok-code-fast-1": _lit8
}),
xai: Type.Object({
"grok-code-fast-1": _lit8,
"grok-2": _lit8,
"grok-2-1212": _lit8,
"grok-2-latest": _lit8,
"grok-2-vision": _lit8,
"grok-2-vision-1212": _lit8,
"grok-2-vision-latest": _lit8,
"grok-3": _lit8,
"grok-3-fast": _lit8,
"grok-3-fast-latest": _lit8,
"grok-3-latest": _lit8,
"grok-3-mini": _lit8,
"grok-3-mini-fast": _lit8,
"grok-3-mini-fast-latest": _lit8,
"grok-3-mini-latest": _lit8,
"grok-4": _lit8,
"grok-4-1-fast": _lit8,
"grok-4-1-fast-non-reasoning": _lit8,
"grok-4-fast": _lit8,
"grok-4-fast-non-reasoning": _lit8,
"grok-4.20-beta-latest-non-reasoning": _lit8,
"grok-4.20-beta-latest-reasoning": _lit8,
"grok-4.20-multi-agent-beta-latest": _lit8,
"grok-beta": _lit8,
"grok-vision-beta": _lit8
}),
groq: Type.Object({
"deepseek-r1-distill-llama-70b": _lit8,
"gemma2-9b-it": _lit8,
"llama-3.1-8b-instant": _lit8,
"llama-3.3-70b-versatile": _lit8,
"llama3-70b-8192": _lit8,
"llama3-8b-8192": _lit8,
"meta-llama/llama-4-maverick-17b-128e-instruct": _lit8,
"meta-llama/llama-4-scout-17b-16e-instruct": _lit8,
"mistral-saba-24b": _lit8,
"moonshotai/kimi-k2-instruct": _lit8,
"moonshotai/kimi-k2-instruct-0905": _lit8,
"openai/gpt-oss-120b": _lit8,
"openai/gpt-oss-20b": _lit8,
"qwen-qwq-32b": _lit8,
"qwen/qwen3-32b": _lit8
}),
cerebras: Type.Object({
"gpt-oss-120b": _lit8,
"llama3.1-8b": _lit8,
"qwen-3-235b-a22b-instruct-2507": _lit8,
"zai-glm-4.7": _lit8
}),
openrouter: Type.Object({
auto: _lit8,
"openai/gpt-oss-120b": _lit8,
"openai/gpt-oss-20b": _lit8,
"qwen/qwen3-32b": _lit8,
"ai21/jamba-large-1.7": _lit8,
"alibaba/tongyi-deepresearch-30b-a3b": _lit8,
"allenai/olmo-3.1-32b-instruct": _lit8,
"amazon/nova-2-lite-v1": _lit8,
"amazon/nova-lite-v1": _lit8,
"amazon/nova-micro-v1": _lit8,
"amazon/nova-premier-v1": _lit8,
"amazon/nova-pro-v1": _lit8,
"anthropic/claude-3-haiku": _lit8,
"anthropic/claude-3.5-haiku": _lit8,
"anthropic/claude-3.5-sonnet": _lit8,
"anthropic/claude-3.7-sonnet": _lit8,
"anthropic/claude-3.7-sonnet:thinking": _lit8,
"anthropic/claude-haiku-4.5": _lit8,
"anthropic/claude-opus-4": _lit8,
"anthropic/claude-opus-4.1": _lit8,
"anthropic/claude-opus-4.5": _lit8,
"anthropic/claude-opus-4.6": _lit8,
"anthropic/claude-sonnet-4": _lit8,
"anthropic/claude-sonnet-4.5": _lit8,
"anthropic/claude-sonnet-4.6": _lit8,
"arcee-ai/trinity-large-preview:free": _lit8,
"arcee-ai/trinity-mini": _lit8,
"arcee-ai/trinity-mini:free": _lit8,
"arcee-ai/virtuoso-large": _lit8,
"baidu/ernie-4.5-21b-a3b": _lit8,
"baidu/ernie-4.5-vl-28b-a3b": _lit8,
"bytedance-seed/seed-1.6": _lit8,
"bytedance-seed/seed-1.6-flash": _lit8,
"bytedance-seed/seed-2.0-lite": _lit8,
"bytedance-seed/seed-2.0-mini": _lit8,
"cohere/command-r-08-2024": _lit8,
"cohere/command-r-plus-08-2024": _lit8,
"deepseek/deepseek-chat": _lit8,
"deepseek/deepseek-chat-v3-0324": _lit8,
"deepseek/deepseek-chat-v3.1": _lit8,
"deepseek/deepseek-r1": _lit8,
"deepseek/deepseek-r1-0528": _lit8,
"deepseek/deepseek-v3.1-terminus": _lit8,
"deepseek/deepseek-v3.2": _lit8,
"deepseek/deepseek-v3.2-exp": _lit8,
"essentialai/rnj-1-instruct": _lit8,
"google/gemini-2.0-flash-001": _lit8,
"google/gemini-2.0-flash-lite-001": _lit8,
"google/gemini-2.5-flash": _lit8,
"google/gemini-2.5-flash-lite": _lit8,
"google/gemini-2.5-flash-lite-preview-09-2025": _lit8,
"google/gemini-2.5-pro": _lit8,
"google/gemini-2.5-pro-preview": _lit8,
"google/gemini-2.5-pro-preview-05-06": _lit8,
"google/gemini-3-flash-preview": _lit8,
"google/gemini-3-pro-preview": _lit8,
"google/gemini-3.1-flash-lite-preview": _lit8,
"google/gemini-3.1-pro-preview": _lit8,
"google/gemini-3.1-pro-preview-customtools": _lit8,
"google/gemma-3-27b-it": _lit8,
"google/gemma-3-27b-it:free": _lit8,
"inception/mercury": _lit8,
"inception/mercury-2": _lit8,
"inception/mercury-coder": _lit8,
"kwaipilot/kat-coder-pro": _lit8,
"meituan/longcat-flash-chat": _lit8,
"meta-llama/llama-3-8b-instruct": _lit8,
"meta-llama/llama-3.1-70b-instruct": _lit8,
"meta-llama/llama-3.1-8b-instruct": _lit8,
"meta-llama/llama-3.3-70b-instruct": _lit8,
"meta-llama/llama-3.3-70b-instruct:free": _lit8,
"meta-llama/llama-4-maverick": _lit8,
"meta-llama/llama-4-scout": _lit8,
"minimax/minimax-m1": _lit8,
"minimax/minimax-m2": _lit8,
"minimax/minimax-m2.1": _lit8,
"minimax/minimax-m2.5": _lit8,
"minimax/minimax-m2.5:free": _lit8,
"mistralai/codestral-2508": _lit8,
"mistralai/devstral-2512": _lit8,
"mistralai/devstral-medium": _lit8,
"mistralai/devstral-small": _lit8,
"mistralai/ministral-14b-2512": _lit8,
"mistralai/ministral-3b-2512": _lit8,
"mistralai/ministral-8b-2512": _lit8,
"mistralai/mistral-large": _lit8,
"mistralai/mistral-large-2407": _lit8,
"mistralai/mistral-large-2411": _lit8,
"mistralai/mistral-large-2512": _lit8,
"mistralai/mistral-medium-3": _lit8,
"mistralai/mistral-medium-3.1": _lit8,
"mistralai/mistral-nemo": _lit8,
"mistralai/mistral-saba": _lit8,
"mistralai/mistral-small-24b-instruct-2501": _lit8,
"mistralai/mistral-small-2603": _lit8,
"mistralai/mistral-small-3.1-24b-instruct:free": _lit8,
"mistralai/mistral-small-3.2-24b-instruct": _lit8,
"mistralai/mistral-small-creative": _lit8,
"mistralai/mixtral-8x22b-instruct": _lit8,
"mistralai/mixtral-8x7b-instruct": _lit8,
"mistralai/pixtral-large-2411": _lit8,
"mistralai/voxtral-small-24b-2507": _lit8,
"moonshotai/kimi-k2": _lit8,
"moonshotai/kimi-k2-0905": _lit8,
"moonshotai/kimi-k2-thinking": _lit8,
"moonshotai/kimi-k2.5": _lit8,
"nex-agi/deepseek-v3.1-nex-n1": _lit8,
"nvidia/llama-3.1-nemotron-70b-instruct": _lit8,
"nvidia/llama-3.3-nemotron-super-49b-v1.5": _lit8,
"nvidia/nemotron-3-nano-30b-a3b": _lit8,
"nvidia/nemotron-3-nano-30b-a3b:free": _lit8,
"nvidia/nemotron-3-super-120b-a12b:free": _lit8,
"nvidia/nemotron-nano-12b-v2-vl:free": _lit8,
"nvidia/nemotron-nano-9b-v2": _lit8,
"nvidia/nemotron-nano-9b-v2:free": _lit8,
"openai/gpt-3.5-turbo": _lit8,
"openai/gpt-3.5-turbo-0613": _lit8,
"openai/gpt-3.5-turbo-16k": _lit8,
"openai/gpt-4": _lit8,
"openai/gpt-4-0314": _lit8,
"openai/gpt-4-1106-preview": _lit8,
"openai/gpt-4-turbo": _lit8,
"openai/gpt-4-turbo-preview": _lit8,
"openai/gpt-4.1": _lit8,
"openai/gpt-4.1-mini": _lit8,
"openai/gpt-4.1-nano": _lit8,
"openai/gpt-4o": _lit8,
"openai/gpt-4o-2024-05-13": _lit8,
"openai/gpt-4o-2024-08-06": _lit8,
"openai/gpt-4o-2024-11-20": _lit8,
"openai/gpt-4o-audio-preview": _lit8,
"openai/gpt-4o-mini": _lit8,
"openai/gpt-4o-mini-2024-07-18": _lit8,
"openai/gpt-4o:extended": _lit8,
"openai/gpt-5": _lit8,
"openai/gpt-5-codex": _lit8,
"openai/gpt-5-image": _lit8,
"openai/gpt-5-image-mini": _lit8,
"openai/gpt-5-mini": _lit8,
"openai/gpt-5-nano": _lit8,
"openai/gpt-5-pro": _lit8,
"openai/gpt-5.1": _lit8,
"openai/gpt-5.1-chat": _lit8,
"openai/gpt-5.1-codex": _lit8,
"openai/gpt-5.1-codex-max": _lit8,
"openai/gpt-5.1-codex-mini": _lit8,
"openai/gpt-5.2": _lit8,
"openai/gpt-5.2-chat": _lit8,
"openai/gpt-5.2-codex": _lit8,
"openai/gpt-5.2-pro": _lit8,
"openai/gpt-5.3-chat": _lit8,
"openai/gpt-5.3-codex": _lit8,
"openai/gpt-5.4": _lit8,
"openai/gpt-5.4-mini": _lit8,
"openai/gpt-5.4-nano": _lit8,
"openai/gpt-5.4-pro": _lit8,
"openai/gpt-oss-120b:free": _lit8,
"openai/gpt-oss-20b:free": _lit8,
"openai/gpt-oss-safeguard-20b": _lit8,
"openai/o1": _lit8,
"openai/o3": _lit8,
"openai/o3-deep-research": _lit8,
"openai/o3-mini": _lit8,
"openai/o3-mini-high": _lit8,
"openai/o3-pro": _lit8,
"openai/o4-mini": _lit8,
"openai/o4-mini-deep-research": _lit8,
"openai/o4-mini-high": _lit8,
"openrouter/auto": _lit8,
"openrouter/free": _lit8,
"openrouter/healer-alpha": _lit8,
"openrouter/hunter-alpha": _lit8,
"prime-intellect/intellect-3": _lit8,
"qwen/qwen-2.5-72b-instruct": _lit8,
"qwen/qwen-2.5-7b-instruct": _lit8,
"qwen/qwen-max": _lit8,
"qwen/qwen-plus": _lit8,
"qwen/qwen-plus-2025-07-28": _lit8,
"qwen/qwen-plus-2025-07-28:thinking": _lit8,
"qwen/qwen-turbo": _lit8,
"qwen/qwen-vl-max": _lit8,
"qwen/qwen3-14b": _lit8,
"qwen/qwen3-235b-a22b": _lit8,
"qwen/qwen3-235b-a22b-2507": _lit8,
"qwen/qwen3-235b-a22b-thinking-2507": _lit8,
"qwen/qwen3-30b-a3b": _lit8,
"qwen/qwen3-30b-a3b-instruct-2507": _lit8,
"qwen/qwen3-30b-a3b-thinking-2507": _lit8,
"qwen/qwen3-4b:free": _lit8,
"qwen/qwen3-8b": _lit8,
"qwen/qwen3-coder": _lit8,
"qwen/qwen3-coder-30b-a3b-instruct": _lit8,
"qwen/qwen3-coder-flash": _lit8,
"qwen/qwen3-coder-next": _lit8,
"qwen/qwen3-coder-plus": _lit8,
"qwen/qwen3-coder:free": _lit8,
"qwen/qwen3-max": _lit8,
"qwen/qwen3-max-thinking": _lit8,
"qwen/qwen3-next-80b-a3b-instruct": _lit8,
"qwen/qwen3-next-80b-a3b-instruct:free": _lit8,
"qwen/qwen3-next-80b-a3b-thinking": _lit8,
"qwen/qwen3-vl-235b-a22b-instruct": _lit8,
"qwen/qwen3-vl-235b-a22b-thinking": _lit8,
"qwen/qwen3-vl-30b-a3b-instruct": _lit8,
"qwen/qwen3-vl-30b-a3b-thinking": _lit8,
"qwen/qwen3-vl-32b-instruct": _lit8,
"qwen/qwen3-vl-8b-instruct": _lit8,
"qwen/qwen3-vl-8b-thinking": _lit8,
"qwen/qwen3.5-122b-a10b": _lit8,
"qwen/qwen3.5-27b": _lit8,
"qwen/qwen3.5-35b-a3b": _lit8,
"qwen/qwen3.5-397b-a17b": _lit8,
"qwen/qwen3.5-9b": _lit8,
"qwen/qwen3.5-flash-02-23": _lit8,
"qwen/qwen3.5-plus-02-15": _lit8,
"qwen/qwq-32b": _lit8,
"relace/relace-search": _lit8,
"sao10k/l3-euryale-70b": _lit8,
"sao10k/l3.1-euryale-70b": _lit8,
"stepfun/step-3.5-flash": _lit8,
"stepfun/step-3.5-flash:free": _lit8,
"thedrummer/rocinante-12b": _lit8,
"thedrummer/unslopnemo-12b": _lit8,
"tngtech/deepseek-r1t2-chimera": _lit8,
"upstage/solar-pro-3": _lit8,
"x-ai/grok-3": _lit8,
"x-ai/grok-3-beta": _lit8,
"x-ai/grok-3-mini": _lit8,
"x-ai/grok-3-mini-beta": _lit8,
"x-ai/grok-4": _lit8,
"x-ai/grok-4-fast": _lit8,
"x-ai/grok-4.1-fast": _lit8,
"x-ai/grok-4.20-beta": _lit8,
"x-ai/grok-code-fast-1": _lit8,
"xiaomi/mimo-v2-flash": _lit8,
"z-ai/glm-4-32b": _lit8,
"z-ai/glm-4.5": _lit8,
"z-ai/glm-4.5-air": _lit8,
"z-ai/glm-4.5-air:free": _lit8,
"z-ai/glm-4.5v": _lit8,
"z-ai/glm-4.6": _lit8,
"z-ai/glm-4.6v": _lit8,
"z-ai/glm-4.7": _lit8,
"z-ai/glm-4.7-flash": _lit8,
"z-ai/glm-5": _lit8,
"z-ai/glm-5-turbo": _lit8
}),
"vercel-ai-gateway": Type.Object({
"openai/gpt-oss-20b": _lit1,
"anthropic/claude-3-haiku": _lit1,
"anthropic/claude-3.5-haiku": _lit1,
"anthropic/claude-3.5-sonnet": _lit1,
"anthropic/claude-3.7-sonnet": _lit1,
"anthropic/claude-haiku-4.5": _lit1,
"anthropic/claude-opus-4": _lit1,
"anthropic/claude-opus-4.1": _lit1,
"anthropic/claude-opus-4.5": _lit1,
"anthropic/claude-opus-4.6": _lit1,
"anthropic/claude-sonnet-4": _lit1,
"anthropic/claude-sonnet-4.5": _lit1,
"anthropic/claude-sonnet-4.6": _lit1,
"deepseek/deepseek-r1": _lit1,
"deepseek/deepseek-v3.1-terminus": _lit1,
"deepseek/deepseek-v3.2": _lit1,
"google/gemini-2.5-flash": _lit1,
"google/gemini-2.5-flash-lite": _lit1,
"google/gemini-2.5-pro": _lit1,
"google/gemini-3-pro-preview": _lit1,
"google/gemini-3.1-flash-lite-preview": _lit1,
"google/gemini-3.1-pro-preview": _lit1,
"inception/mercury-2": _lit1,
"meituan/longcat-flash-chat": _lit1,
"minimax/minimax-m2": _lit1,
"minimax/minimax-m2.1": _lit1,
"minimax/minimax-m2.5": _lit1,
"moonshotai/kimi-k2": _lit1,
"moonshotai/kimi-k2-0905": _lit1,
"moonshotai/kimi-k2-thinking": _lit1,
"moonshotai/kimi-k2.5": _lit1,
"nvidia/nemotron-nano-9b-v2": _lit1,
"openai/gpt-4-turbo": _lit1,
"openai/gpt-4.1": _lit1,
"openai/gpt-4.1-mini": _lit1,
"openai/gpt-4.1-nano": _lit1,
"openai/gpt-4o": _lit1,
"openai/gpt-4o-mini": _lit1,
"openai/gpt-5": _lit1,
"openai/gpt-5-codex": _lit1,
"openai/gpt-5-mini": _lit1,
"openai/gpt-5-nano": _lit1,
"openai/gpt-5-pro": _lit1,
"openai/gpt-5.1-codex": _lit1,
"openai/gpt-5.1-codex-max": _lit1,
"openai/gpt-5.1-codex-mini": _lit1,
"openai/gpt-5.2": _lit1,
"openai/gpt-5.2-chat": _lit1,
"openai/gpt-5.2-codex": _lit1,
"openai/gpt-5.2-pro": _lit1,
"openai/gpt-5.3-chat": _lit1,
"openai/gpt-5.3-codex": _lit1,
"openai/gpt-5.4": _lit1,
"openai/gpt-5.4-mini": _lit1,
"openai/gpt-5.4-nano": _lit1,
"openai/gpt-5.4-pro": _lit1,
"openai/gpt-oss-safeguard-20b": _lit1,
"openai/o1": _lit1,
"openai/o3": _lit1,
"openai/o3-deep-research": _lit1,
"openai/o3-mini": _lit1,
"openai/o3-pro": _lit1,
"openai/o4-mini": _lit1,
"prime-intellect/intellect-3": _lit1,
"xiaomi/mimo-v2-flash": _lit1,
"alibaba/qwen-3-14b": _lit1,
"alibaba/qwen-3-235b": _lit1,
"alibaba/qwen-3-30b": _lit1,
"alibaba/qwen-3-32b": _lit1,
"alibaba/qwen3-235b-a22b-thinking": _lit1,
"alibaba/qwen3-coder": _lit1,
"alibaba/qwen3-coder-30b-a3b": _lit1,
"alibaba/qwen3-coder-next": _lit1,
"alibaba/qwen3-coder-plus": _lit1,
"alibaba/qwen3-max": _lit1,
"alibaba/qwen3-max-preview": _lit1,
"alibaba/qwen3-max-thinking": _lit1,
"alibaba/qwen3-vl-thinking": _lit1,
"alibaba/qwen3.5-flash": _lit1,
"alibaba/qwen3.5-plus": _lit1,
"anthropic/claude-3.5-sonnet-20240620": _lit1,
"arcee-ai/trinity-large-preview": _lit1,
"bytedance/seed-1.6": _lit1,
"cohere/command-a": _lit1,
"deepseek/deepseek-v3": _lit1,
"deepseek/deepseek-v3.1": _lit1,
"deepseek/deepseek-v3.2-thinking": _lit1,
"google/gemini-2.0-flash": _lit1,
"google/gemini-2.0-flash-lite": _lit1,
"google/gemini-3-flash": _lit1,
"inception/mercury-coder-small": _lit1,
"meituan/longcat-flash-thinking": _lit1,
"meta/llama-3.1-70b": _lit1,
"meta/llama-3.1-8b": _lit1,
"meta/llama-3.2-11b": _lit1,
"meta/llama-3.2-90b": _lit1,
"meta/llama-3.3-70b": _lit1,
"meta/llama-4-maverick": _lit1,
"meta/llama-4-scout": _lit1,
"minimax/minimax-m2.1-lightning": _lit1,
"minimax/minimax-m2.5-highspeed": _lit1,
"mistral/codestral": _lit1,
"mistral/devstral-2": _lit1,
"mistral/devstral-small": _lit1,
"mistral/devstral-small-2": _lit1,
"mistral/ministral-3b": _lit1,
"mistral/ministral-8b": _lit1,
"mistral/mistral-medium": _lit1,
"mistral/mistral-small": _lit1,
"mistral/pixtral-12b": _lit1,
"mistral/pixtral-large": _lit1,
"moonshotai/kimi-k2-thinking-turbo": _lit1,
"moonshotai/kimi-k2-turbo": _lit1,
"nvidia/nemotron-nano-12b-v2-vl": _lit1,
"openai/gpt-5-chat": _lit1,
"openai/gpt-5.1-instant": _lit1,
"openai/gpt-5.1-thinking": _lit1,
"perplexity/sonar": _lit1,
"perplexity/sonar-pro": _lit1,
"xai/grok-2-vision": _lit1,
"xai/grok-3": _lit1,
"xai/grok-3-fast": _lit1,
"xai/grok-3-mini": _lit1,
"xai/grok-3-mini-fast": _lit1,
"xai/grok-4": _lit1,
"xai/grok-4-fast-non-reasoning": _lit1,
"xai/grok-4-fast-reasoning": _lit1,
"xai/grok-4.1-fast-non-reasoning": _lit1,
"xai/grok-4.1-fast-reasoning": _lit1,
"xai/grok-4.20-multi-agent-beta": _lit1,
"xai/grok-4.20-non-reasoning-beta": _lit1,
"xai/grok-4.20-reasoning-beta": _lit1,
"xai/grok-code-fast-1": _lit1,
"zai/glm-4.5": _lit1,
"zai/glm-4.5-air": _lit1,
"zai/glm-4.5v": _lit1,
"zai/glm-4.6": _lit1,
"zai/glm-4.6v": _lit1,
"zai/glm-4.6v-flash": _lit1,
"zai/glm-4.7": _lit1,
"zai/glm-4.7-flash": _lit1,
"zai/glm-4.7-flashx": _lit1,
"zai/glm-5": _lit1,
"zai/glm-5-turbo": _lit1
}),
zai: Type.Object({
"glm-4.5": _lit8,
"glm-4.5-air": _lit8,
"glm-4.5-flash": _lit8,
"glm-4.5v": _lit8,
"glm-4.6": _lit8,
"glm-4.6v": _lit8,
"glm-4.7": _lit8,
"glm-4.7-flash": _lit8,
"glm-5": _lit8,
"glm-5-turbo": _lit8
}),
mistral: Type.Object({
"codestral-latest": _lit9,
"devstral-2512": _lit9,
"devstral-medium-2507": _lit9,
"devstral-medium-latest": _lit9,
"devstral-small-2505": _lit9,
"devstral-small-2507": _lit9,
"labs-devstral-small-2512": _lit9,
"magistral-medium-latest": _lit9,
"magistral-small": _lit9,
"ministral-3b-latest": _lit9,
"ministral-8b-latest": _lit9,
"mistral-large-2411": _lit9,
"mistral-large-2512": _lit9,
"mistral-large-latest": _lit9,
"mistral-medium-2505": _lit9,
"mistral-medium-2508": _lit9,
"mistral-medium-latest": _lit9,
"mistral-nemo": _lit9,
"mistral-small-2506": _lit9,
"mistral-small-latest": _lit9,
"open-mistral-7b": _lit9,
"open-mixtral-8x22b": _lit9,
"open-mixtral-8x7b": _lit9,
"pixtral-12b": _lit9,
"pixtral-large-latest": _lit9
}),
minimax: Type.Object({
"MiniMax-M2": _lit1,
"MiniMax-M2.1": _lit1,
"MiniMax-M2.5": _lit1,
"MiniMax-M2.5-highspeed": _lit1
}),
"minimax-cn": Type.Object({
"MiniMax-M2": _lit1,
"MiniMax-M2.1": _lit1,
"MiniMax-M2.5": _lit1,
"MiniMax-M2.5-highspeed": _lit1
}),
huggingface: Type.Object({
"MiniMaxAI/MiniMax-M2.1": _lit8,
"MiniMaxAI/MiniMax-M2.5": _lit8,
"Qwen/Qwen3-235B-A22B-Thinking-2507": _lit8,
"Qwen/Qwen3-Coder-480B-A35B-Instruct": _lit8,
"Qwen/Qwen3-Coder-Next": _lit8,
"Qwen/Qwen3-Next-80B-A3B-Instruct": _lit8,
"Qwen/Qwen3-Next-80B-A3B-Thinking": _lit8,
"Qwen/Qwen3.5-397B-A17B": _lit8,
"XiaomiMiMo/MiMo-V2-Flash": _lit8,
"deepseek-ai/DeepSeek-R1-0528": _lit8,
"deepseek-ai/DeepSeek-V3.2": _lit8,
"moonshotai/Kimi-K2-Instruct": _lit8,
"moonshotai/Kimi-K2-Instruct-0905": _lit8,
"moonshotai/Kimi-K2-Thinking": _lit8,
"moonshotai/Kimi-K2.5": _lit8,
"zai-org/GLM-4.7": _lit8,
"zai-org/GLM-4.7-Flash": _lit8,
"zai-org/GLM-5": _lit8
}),
opencode: Type.Object({
"claude-haiku-4-5": _lit1,
"claude-opus-4-1": _lit1,
"claude-opus-4-5": _lit1,
"claude-opus-4-6": _lit1,
"claude-sonnet-4-5": _lit1,
"claude-sonnet-4-6": _lit1,
"gemini-3-flash": _lit2,
"gpt-5": _lit5,
"gpt-5-codex": _lit5,
"gpt-5-nano": _lit5,
"gpt-5.1": _lit5,
"gpt-5.1-codex": _lit5,
"gpt-5.1-codex-max": _lit5,
"gpt-5.1-codex-mini": _lit5,
"gpt-5.2": _lit5,
"gpt-5.2-codex": _lit5,
"gpt-5.3-codex": _lit5,
"gpt-5.4": _lit5,
"gpt-5.4-pro": _lit5,
"claude-sonnet-4": _lit1,
"glm-5": _lit8,
"big-pickle": _lit1,
"claude-3-5-haiku": _lit1,
"gemini-3.1-pro": _lit2,
"kimi-k2.5": _lit8,
"mimo-v2-flash-free": _lit8,
"minimax-m2.5": _lit8,
"minimax-m2.5-free": _lit1,
"nemotron-3-super-free": _lit8
}),
"opencode-go": Type.Object({
"glm-5": _lit8,
"kimi-k2.5": _lit8,
"minimax-m2.5": _lit1
}),
"kimi-coding": Type.Object({
k2p5: _lit1,
"kimi-k2-thinking": _lit1
})
})
